---
permalink: online-help/concept-nvme-namespace-performance-explorer-page.html
sidebar: sidebar
keywords: 
summary: 'The Namespace Explorer page provides a detailed overview of the performance of all the Namespaces within a cluster.'
---
= Namespace Explorer page
:icons: font
:imagesdir: ../media/

[.lead]
The Namespace Explorer page provides a detailed overview of the performance of all the Namespaces within a cluster.

The Namespace Explorer page enables you to track and compare Namespace performance during a specific time period, which helps you to troubleshoot and fine-tune the performance of your Namespaces.

Using the View and Compare functionality you can compare the performance of this Namespace with:

* the volume on which the Namespace resides
* other Namespaces that are on the same volume
* other Namespaces that are on the same SVM

The Namespace Explorer page enables you to:

* View threshold-related issues and their details
* Track and compare Namespace performance data
* Investigate and troubleshoot threshold-related issues
* Investigate and troubleshoot performance issues
* Launch System Manager to make a configuration change to the Namespace
+
The *Configure Namespace* button is available if you are logged in to Unified Manager with the OnCommand Administrator or Storage Administrator role, and when using ONTAP 9.5 or greater.
