---
permalink: online-help/concept_what_alerts_are.html
sidebar: sidebar
keywords: 
summary: 'While events occur continuously, the Unified Manager generates an alert only when an event meets specified filter criteria. You can choose the events for which alerts should be generated—for example, when a space threshold is exceeded or an object goes offline. You can also associate an alert with a script that is executed when an alert is triggered.'
---
= What alerts are
:icons: font
:imagesdir: ../media/

[.lead]
While events occur continuously, the Unified Manager generates an alert only when an event meets specified filter criteria. You can choose the events for which alerts should be generated--for example, when a space threshold is exceeded or an object goes offline. You can also associate an alert with a script that is executed when an alert is triggered.

Filter criteria include object class, name, or event severity.

*Related information*

xref:concept_what_health_events_are.adoc[What health events are]

xref:concept_what_performance_events_are.adoc[What performance events are]

xref:concept_what_event_management_system_events_are.adoc[What Event Management System events are]

xref:concept_managing_scripts.adoc[Managing scripts]
