---
permalink: online-help/concept-unified-manager-databases-accessible-for-reporting.html
sidebar: sidebar
keywords: 
summary: 'Unified Manager uses a MySQL database to store data from the clusters that it is monitoring. Data is persisted into various schemas in the MySQL database.'
---
= Unified Manager databases accessible for custom reporting
:icons: font
:imagesdir: ../media/

[.lead]
Unified Manager uses a MySQL database to store data from the clusters that it is monitoring. Data is persisted into various schemas in the MySQL database.

Starting with Unified Manager 7.3, additional schemas are exposed that provide access to additional table data.

All table data from the following databases are available:

[options="header"]
|===
| Database| Description
a|
netapp_model_view
a|
Data about the objects on ONTAP controllers.
a|
netapp_performance
a|
Cluster specific performance counters.
a|
ocum
a|
Unified Manager application data and information to support UI filtering, sorting, and the calculation of some derived fields.
a|
ocum_report
a|
Data for inventory configuration and capacity-related information.
a|
ocum_report_birt
a|
Same as above, but this database is consumed by built-in BIRT reports.
a|
opm
a|
Performance configuration settings and threshold information.
a|
scalemonitor
a|
Data about the Unified Manager application health and performance issues.
|===
A reporting user -- a Database user with the Report Schema role -- is able to access the data in these tables. This user has read-only access to reporting and other database views directly from the Unified Manager database. Note that this user does not have permission to access any tables that contain user data or cluster credential information.

See the http://www.netapp.com/us/media/tr-4565.pdf[Technical Report for Unified Manager Reporting] (TR-4565) for more details.

*Related information*

xref:task-adding-users.adoc[Adding users]
