---
permalink: online-help/concept_cluster_performance_explorer_page.html
sidebar: sidebar
keywords: 
summary: 'The Performance/Cluster Explorer page provides a detailed performance overview of all the clusters that are managed by Unified Manager.'
---
= Performance/Cluster Explorer page
:icons: font
:imagesdir: ../media/

[.lead]
The Performance/Cluster Explorer page provides a detailed performance overview of all the clusters that are managed by Unified Manager.

The Performance/Cluster Explorer page enables you to track cluster performance and compare the objects within that cluster during a specific time period, which helps in troubleshooting and fine-tuning the performance of a cluster.

Using the View and Compare functionality you can compare the performance of the cluster with:

* the nodes on this cluster
* the storage virtual machines (SVMs) of this cluster
* the aggregates on this cluster

The Performance/Cluster Explorer page enables you to:

* View threshold-related issues and their details
* Track cluster performance data
* Investigate and troubleshoot threshold-related issues
* Investigate and troubleshoot performance issues

*Related information*

xref:concept_components_of_the_performance_explorer_page.adoc[Components of the Performance Explorer page]

xref:reference_summary_page_opm.adoc[Summary page]

xref:task_defining_the_list_of_correlated_objects_for_comparison_graphing.adoc[Defining the list of correlated objects for comparison graphing]

xref:reference_types_of_performance_counter_charts.adoc[Types of performance counter charts]

xref:task_selecting_performance_charts_to_display.adoc[Selecting performance charts to display]

xref:concept_counter_charts_zoom_view.adoc[Counter Charts Zoom View]
