---
permalink: online-help/concept-what-the-expected-range-of-performance-is.html
sidebar: sidebar
keywords: 
summary: 'The expected range of values is a forecast, or prediction, of what the upper and lower performance values are expected to be at a specific time. For the workload latency, the upper values form the performance threshold. When the actual value crosses the performance threshold, Unified Manager triggers a performance event alert.'
---
= What the expected range of performance is
:icons: font
:imagesdir: ../media/

[.lead]
The expected range of values is a forecast, or prediction, of what the upper and lower performance values are expected to be at a specific time. For the workload latency, the upper values form the performance threshold. When the actual value crosses the performance threshold, Unified Manager triggers a performance event alert.

For example, during regular business hours between 9:00 a.m. and 5:00 p.m., most employees might check their email between 9:00 a.m. and 10:30 a.m. The increased demand on the email servers means an increase in workload activity on the back-end storage during this time. Employees might notice slow response time from their email clients.

During the lunch hour between 12:00 p.m. and 1:00 p.m. and at the end of the work day after 5:00 p.m., most employees are likely away from their computers. The demand on the email servers typically decreases, also decreasing the demand on back-end storage. Alternatively, there could be scheduled workload operations, such as storage backups or virus scanning, that start after 5:00 p.m. and increase activity on the back-end storage.

Over several days, the increase and decrease in workload activity determines the expected range of activity, with upper and lower boundaries for a workload. When the actual workload activity for an object is outside the upper or lower boundaries, and remains outside the boundaries for a period of time, this might indicate that the object is being overused or underused.

== How the expected range is formed

Unified Manager must collect a minimum of 3 days of workload activity before it can begin its analysis and before the expected range for I/O response time and operations can be displayed in the GUI. The minimum required data collection does not account for all changes occurring from workload activity. After collecting the first 3 days of activity, Unified Manager adjusts the expected range, every 24 hours at 12:00 a.m., to reflect workload activity changes and establish a more accurate performance threshold.

[NOTE]
====
Daylight savings time (DST) changes the system time, which alters the expected range of performance statistics for monitored workloads. Unified Manager immediately begins to correct the expected range, which takes approximately 15 days to complete. During this time you can continue to use Unified Manager, but, since Unified Manager uses the expected range to detect events, some events might not be accurate. Events detected prior to the time change are not affected. Manually changing the time on a cluster, or on a Unified Manager server, to an earlier time will also affect the event analysis results.
====

*Related information*

xref:concept-collecting-data-and-monitoring-workload-performance.adoc[Collecting data and monitoring workload performance]

xref:reference-how-the-expected-range-is-used-in-performance-analysis.adoc[How the expected range is used in performance analysis]

xref:reference-performance-event-analysis-and-notification.adoc[Performance event analysis and notification]

xref:reference-workload-performance-measurement-values.adoc[Workload performance measurement values]

xref:task-determining-whether-a-workload-has-a-performance-issue.adoc[Determining whether a workload has a performance issue]
