---
permalink: online-help/concept-what-report-importing-is.html
sidebar: sidebar
keywords: 
summary: 'You can import a report using the Import Report option from Unified Manager and save the imported report with a name and a brief description. By importing reports, you can add custom reports to your environment in addition to the standard reports provided in Unified Manager.'
---
= What report importing is
:icons: font
:imagesdir: ../media/

[.lead]
You can import a report using the *Import Report* option from Unified Manager and save the imported report with a name and a brief description. By importing reports, you can add custom reports to your environment in addition to the standard reports provided in Unified Manager.

You can import a `.rptdesign` file that is already created. You can run, share, schedule, and delete an imported report.

Unified Manager stores the import report log files in the files jboss.log, ocum-report.log, and ocumserver-debug.log.

[NOTE]
====
Customer support will not assist with designing reports, but they will support you with issues faced during a report import operation.
====

The import report feature includes the following support:

* Reports with multiple headers, in which the column span is set to 1 (`colspan=1`)
* Reports with charts only
* Reports with lists and grid only
* Passwords used in reports must be encoded using "`base64`" format. Reports using other encoding, for example, "`jce`" format, will cause an error during the import process.
* Reports containing data aggregation should include the aggregated column element in the table data of the report.

Reports in text, CSV, and Excel formats are supported in the following scenarios:

* Table element only in the `.rptdesign` file
* A table with only one header row

[NOTE]
====
You cannot import reports that have a column span of more than 1. If a report in text, CSV, or Excel format has more than one-header row, only the first header row is considered, and the rest are ignored.
====
