---
permalink: online-help/concept-analyzing-events-from-system-defined-performance-thresholds.html
sidebar: sidebar
keywords: 
summary: 'Events generated from system-defined performance thresholds indicate that a performance counter, or set of performance counters, for a certain storage object has crossed the threshold from a system-defined policy. This indicates that the storage object, for example, an aggregate or node, is experiencing a performance issue.'
---
= Analyzing events from system-defined performance thresholds
:icons: font
:imagesdir: ../media/

[.lead]
Events generated from system-defined performance thresholds indicate that a performance counter, or set of performance counters, for a certain storage object has crossed the threshold from a system-defined policy. This indicates that the storage object, for example, an aggregate or node, is experiencing a performance issue.

You use the Event details page to analyze the performance event and take corrective action, if necessary, to return performance back to normal.

[NOTE]
====
System-defined threshold policies are not enabled on Cloud Volumes ONTAP, ONTAP Edge, or ONTAP Select systems.
====

*Related information*

xref:reference-event-details-page.adoc[Event details page]

xref:task-checking-the-health-of-clusters-in-a-metrocluster-configuration.adoc[Checking the health of clusters in a MetroCluster configuration]

xref:reference-list-of-events-and-severity-types.adoc[List of events and severity types]

xref:reference-types-of-system-defined-performance-threshold-policies.adoc[Types of system-defined performance threshold policies]
