---
permalink: online-help/concept_analyzing_events_from_system_defined_performance_thresholds.html
sidebar: sidebar
keywords: 
summary: 'Events generated from system-defined performance thresholds indicate that a performance counter, or set of performance counters, for a certain storage object has crossed the threshold from a system-defined policy. This indicates that the storage object, for example, an aggregate or node, is experiencing a performance issue.'
---
= Analyzing events from system-defined performance thresholds
:icons: font
:imagesdir: ../media/

[.lead]
Events generated from system-defined performance thresholds indicate that a performance counter, or set of performance counters, for a certain storage object has crossed the threshold from a system-defined policy. This indicates that the storage object, for example, an aggregate or node, is experiencing a performance issue.

You use the Event details page to analyze the performance event and take corrective action, if necessary, to return performance back to normal.

[NOTE]
====
System-defined threshold policies are not enabled on Cloud Volumes ONTAP, ONTAP Edge, or ONTAP Select systems.
====

*Related information*

xref:reference_event_details_page.adoc[Event details page]

xref:task_checking_the_health_of_clusters_in_a_metrocluster_configuration.adoc[Checking the health of clusters in a MetroCluster configuration]

xref:reference_list_of_events_and_severity_types.adoc[List of events and severity types]

xref:reference_types_of_system_defined_performance_threshold_policies.adoc[Types of system-defined performance threshold policies]
