---
permalink: online-help/concept_understanding_svm_associations.html
sidebar: sidebar
keywords: 
summary: 'storage virtual machine \(SVM\) associations are mappings from a source SVM to a destination SVM that are used by partner applications for resource selection and secondary volume provisioning.'
---
= Understanding SVM associations
:icons: font
:imagesdir: ../media/

[.lead]
storage virtual machine (SVM) associations are mappings from a source SVM to a destination SVM that are used by partner applications for resource selection and secondary volume provisioning.

Associations are always created between a source SVM and a destination SVM, regardless of whether the destination SVM is a secondary destination or a tertiary destination. You cannot use a secondary destination SVM as a source to create an association with a tertiary destination SVM.

You can associate SVMs in three ways:

* Associate any SVM
+
You can create an association between any primary source SVM and one or more destination SVMs. This means that all existing SVMs that currently require protection, as well as any SVMs that are created in the future, are associated with the specified destination SVMs. For example, you might want applications from several different sources at different locations to be backed up to one or more destination SVMs in one location.

* Associate a particular SVM
+
You can create an association between a specific source SVM and one or more specific destination SVMs. For example, if you are providing storage services to many clients whose data must be separate from one another, you can choose this option to associate a specific source SVM to a specific destination SVM that is assigned to only that client.

* Associate with an external SVM
+
You can create an association between a source SVM and an external flexible volume of a destination SVM.
