---
permalink: online-help/concept_what_the_default_rule_is.html
sidebar: sidebar
keywords: 
summary: 'The default rule is the rule present in the data policy of a storage virtual machine \(SVM\) with Infinite Volume. It is used to determine the placement of data written to the Infinite Volume when none of the conditions in the existing rules match with the data being written.'
---
= What the default rule is
:icons: font
:imagesdir: ../media/

[.lead]
The default rule is the rule present in the data policy of a storage virtual machine (SVM) with Infinite Volume. It is used to determine the placement of data written to the Infinite Volume when none of the conditions in the existing rules match with the data being written.

The default rule is always the last rule in a data policy and cannot be reordered. For example, consider a data policy with three rules. Rule-1 places all .pdf files in the __high_performance__storage class. Rule-2 places all files owned by the administrator and file names that end with *.xls in the _archival_constituent_ storage class. The third rule is the default rule with the _low_performance_ storage class.

When a set of *.jpg files that are not owned by the administrator is written to the Infinite Volume, the default rule is used to place these .jpg files in the _low_performance_ storage class. Rule-1 and Rule-2 are not used because the data that is written does not match these rules.

*Related information*

xref:concept_what_rules_and_data_policies_are.adoc[What rules and data policies are]
