---
permalink: online-help/concept-storage-vm-performance-explorer-page.html
sidebar: sidebar
keywords: 
summary: 'The Performance/SVM Explorer page provides a detailed performance overview of all the storage virtual machines \(SVMs\) in a cluster.'
---
= Performance/SVM Explorer page
:icons: font
:imagesdir: ../media/

[.lead]
The Performance/SVM Explorer page provides a detailed performance overview of all the storage virtual machines (SVMs) in a cluster.

The Performance/SVM Explorer page enables you to track and compare SVM performance during a specific time period, which helps you to troubleshoot and fine-tune your SVM performance.

Using the View and Compare functionality you can compare the performance of this SVM with:

* other SVMs on the same cluster
* the volumes on this SVM
* the LIFs on this SVM

The Performance/SVM Explorer page enables you to:

* View threshold-related issues and their details
* Track and compare SVM performance data
* Investigate and troubleshoot threshold-related issues
* Investigate and troubleshoot performance issues
