---
permalink: online-help/concept-port-performance-explorer-page.html
sidebar: sidebar
keywords: 
summary: 'The Performance/Port Explorer page provides a detailed performance overview of all ports in a cluster.'
---
= Performance/Port Explorer page
:icons: font
:imagesdir: ../media/

[.lead]
The Performance/Port Explorer page provides a detailed performance overview of all ports in a cluster.

[NOTE]
====
Performance counter values are displayed for physical ports only. Counter values are not displayed for VLANs or interface groups.
====

The Performance/Port Explorer page enables you to track and compare port performance during a specific time period, which helps you to troubleshoot and fine-tune your port performance.

Using the View and Compare functionality you can compare the performance of this port with:

* other ports on the same node
* the node on which the port resides
* LIFs that are on the port

[NOTE]
====
Only cluster and data LIFs are displayed when filtering using the "`LIFs on this port`" option. No intercluster LIFs are shown.
====

The Performance/Port Explorer page enables you to:

* View threshold-related issues and their details
* Track and compare port performance data
* Investigate and troubleshoot threshold-related issues
* Investigate and troubleshoot performance issues
