---
permalink: online-help/reference-manage-report-schedules-dialog-box-um-6-2.html
sidebar: sidebar
keywords: 
summary: 'You can view, modify, or delete existing report schedules and add new schedules for your reports from the Manage Report Schedules dialog box.'
---
= Manage Report Schedules dialog box
:icons: font
:imagesdir: ../media/

[.lead]
You can view, modify, or delete existing report schedules and add new schedules for your reports from the Manage Report Schedules dialog box.

== Properties

You can select an existing schedule or create a new schedule for your reports. You can view, modify, or delete your report schedules.

* *Left pane*
 ** *Schedule Name*
+
Displays the existing schedules. By clicking on any schedule you can view the schedule details in the right pane. For the first login, there are no existing schedules.

 ** *Add Schedule*
+
Displays the new schedule form in the right pane. You can now add a new schedule.
* *Right pane*
 ** *Schedule Name*
+
Displays the schedule name.

 ** *Recipient Email Address*
+
Displays the email address of the user to whom the report must be sent. You can enter more than one email addresses separated by commas.

 ** *Report Format*
+
Displays the format in which the report must be presented. The PDF option is selected as the default report format. If the XHTML format is selected, open the report that is sent by email by using a supported web browser.

 ** *Frequency*
+
Displays the frequency at which the report is scheduled.

 ** *Report Category*
+
Displays the report category groups. Selecting a report category from the list, displays the reports that belong to that report category in the Available Reports column.

 ** *Available Reports*
+
Displays only the reports that belong to the report category selected.

 ** *Selected Reports*
+
Displays the selected reports to which you choose to apply the schedule. You can select the required reports from the Available Reports column. At least one report must be selected

== Command buttons

The command buttons enable you to perform the following tasks:

* *Add Schedule*
+
Enables you to add a new schedule.

* *Delete Schedule*
+
Enables you to delete the schedule being currently viewed. When you create a new schedule, this button is not available.

* *Save*
+
Saves the schedule being viewed, modified, or added.

* *Save and Close*
+
Saves the schedule being viewed, modified, or added and closes the Manage Report Schedules dialog box.

* *Cancel*
+
Closes the Manage Report Schedules dialog box while displaying a message to save the schedule.
