---
permalink: online-help/reference-list-of-available-rest-apis-ocum.html
sidebar: sidebar
keywords: 
summary: 'You should be aware of the available REST APIs in Unified Manager so you can plan how you may use the APIs. The API calls are organized under the various resource types or categories.'
---
= List of available REST APIs
:icons: font
:imagesdir: ../media/

[.lead]
You should be aware of the available REST APIs in Unified Manager so you can plan how you may use the APIs. The API calls are organized under the various resource types or categories.

You must refer to the Swagger web page for a complete list of the available API calls, as well as the details of each call.

The management API calls are organized according to the following categories:

* Aggregates
* Clusters
* Events
* LIFs
* LUNs
* Namespaces
* Nodes
* Ports
* SVMs
* Volumes

When you select one of the categories a list appears that shows the API sub-category along with a versioned sub-category, for example:

* /aggregates
* /v1/aggregates

The newest version of the REST APIs are listed without a version number in the URL. You should always use the newest version of the API to integrate with Unified Manager.
