---
permalink: online-help/reference-schedule-report-dialog-box-um-6-2.html
sidebar: sidebar
keywords: 
summary: 'You can schedule the reports to be generated on a recurring basis at a specified frequency from the Schedule Report dialog box. The report is sent by email to one or more users specified in the Schedule Report dialog box.'
---
= Schedule Report dialog box
:icons: font
:imagesdir: ../media/

[.lead]
You can schedule the reports to be generated on a recurring basis at a specified frequency from the Schedule Report dialog box. The report is sent by email to one or more users specified in the Schedule Report dialog box.

== Properties

You can schedule a report by specifying properties such as the email address of the user, the format of the report, and the frequency at which the report is generated.

* *Using Existing Schedule*
 ** *Schedule Name*
+
Displays all the existing schedule names. You can select an existing schedule for your reports from here.
* *Create New Schedule*
 ** *Schedule Name*
+
Enables you to enter the schedule name while creating a new schedule.

 ** *Recipient Email Address*
+
Specifies the email address of the user to whom you want to send the report. You can specify one or more entries, separated by commas. This is a mandatory field.

 ** *Report Format*
+
Specifies the format in which you want to schedule the report. The _PDF_ option is selected by default.

 ** *Frequency*
+
Specifies the frequency at which you want to schedule the report. The _Hourly_ option is selected by default.

== Command buttons

The command buttons enable you to perform the following tasks:

* *Schedule*
+
Schedules the report with the saved or updated template and closes the Schedule Report dialog box.

* *Cancel*
+
Closes the Schedule Report dialog box while displaying a message to save the schedule report template.

*Related information*

xref:concept-what-report-scheduling-is.adoc[What report scheduling is]

xref:task-scheduling-reports.adoc[Scheduling reports]
