---
permalink: online-help/reference-lun-events.html
sidebar: sidebar
keywords: 
summary: 'LUN events provide you with information about the status of your LUNs, so that you can monitor for potential problems. Events are grouped by impact area and include the event and trap name, impact level, source type, and severity.'
---
= LUN events
:icons: font
:imagesdir: ../media/

[.lead]
LUN events provide you with information about the status of your LUNs, so that you can monitor for potential problems. Events are grouped by impact area and include the event and trap name, impact level, source type, and severity.

== Impact area: availability

An asterisk (*) identifies EMS events that have been converted to Unified Manager events.

[options="header"]
|===
| Event name(Trap name) | Impact level| Source type| Severity
a|
LUN Offline(ocumEvtLunOffline)

a|
Incident
a|
LUN
a|
Critical
a|
LUN Destroyed *
a|
Event
a|
LUN
a|
Information
a|
Single Active Path To Access LUN(ocumEvtLunSingleActivePath)

a|
Risk
a|
LUN
a|
Warning
a|
No Active Paths To Access LUN(ocumEvtLunNotReachable)

a|
Incident
a|
LUN
a|
Critical
a|
No Optimized Paths To Access LUN(ocumEvtLunOptimizedPathInactive)

a|
Risk
a|
LUN
a|
Warning
a|
No Paths To Access LUN From HA Partner(ocumEvtLunHaPathInactive)

a|
Risk
a|
LUN
a|
Warning
|===

== Impact area: capacity

[options="header"]
|===
| Event name(Trap name) | Impact level| Source type| Severity
a|
Insufficient Space For LUN Snapshot Copy(ocumEvtLunSnapshotNotPossible)

a|
Risk
a|
Volume
a|
Warning
|===

== Impact area: performance

[options="header"]
|===
| Event name(Trap name) | Impact level| Source type| Severity
a|
LUN IOPS Critical Threshold Breached(ocumLunIopsIncident)

a|
Incident
a|
LUN
a|
Critical
a|
LUN IOPS Warning Threshold Breached(ocumLunIopsWarning)

a|
Risk
a|
LUN
a|
Warning
a|
LUN MBps Critical Threshold Breached(ocumLunMbpsIncident)

a|
Incident
a|
LUN
a|
Critical
a|
LUN MBps Warning Threshold Breached(ocumLunMbpsWarning)

a|
Risk
a|
LUN
a|
Warning
a|
LUN Latency ms/op Critical Threshold Breached(ocumLunLatencyIncident)

a|
Incident
a|
LUN
a|
Critical
a|
LUN Latency ms/op Warning Threshold Breached(ocumLunLatencyWarning)

a|
Risk
a|
LUN
a|
Warning
a|
LUN Latency and IOPS Critical Threshold Breached(ocumLunLatencyIopsIncident)

a|
Incident
a|
LUN
a|
Critical
a|
LUN Latency and IOPS Warning Threshold Breached(ocumLunLatencyIopsWarning)

a|
Risk
a|
LUN
a|
Warning
a|
LUN Latency and MBps Critical Threshold Breached(ocumLunLatencyMbpsIncident)

a|
Incident
a|
LUN
a|
Critical
a|
LUN Latency and MBps Warning Threshold Breached(ocumLunLatencyMbpsWarning)

a|
Risk
a|
LUN
a|
Warning
a|
LUN Latency and Aggregate Perf. Capacity Used Critical Threshold Breached(ocumLunLatencyAggregatePerfCapacityUsedIncident)

a|
Incident
a|
LUN
a|
Critical
a|
LUN Latency and Aggregate Perf. Capacity Used Warning Threshold Breached(ocumLunLatencyAggregatePerfCapacityUsedWarning)

a|
Risk
a|
LUN
a|
Warning
a|
LUN Latency and Aggregate Utilization Critical Threshold Breached(ocumLunLatencyAggregateUtilizationIncident)

a|
Incident
a|
LUN
a|
Critical
a|
LUN Latency and Aggregate Utilization Warning Threshold Breached(ocumLunLatencyAggregateUtilizationWarning)

a|
Risk
a|
LUN
a|
Warning
a|
LUN Latency and Node Perf. Capacity Used Critical Threshold Breached(ocumLunLatencyNodePerfCapacityUsedIncident)

a|
Incident
a|
LUN
a|
Critical
a|
LUN Latency and Node Perf. Capacity Used Warning Threshold Breached(ocumLunLatencyNodePerfCapacityUsedWarning)

a|
Risk
a|
LUN
a|
Warning
a|
LUN Latency and Node Perf. Capacity Used - Takeover Critical Threshold Breached(ocumLunLatencyAggregatePerfCapacityUsedTakeoverIncident)

a|
Incident
a|
LUN
a|
Critical
a|
LUN Latency and Node Perf. Capacity Used - Takeover Warning Threshold Breached(ocumLunLatencyAggregatePerfCapacityUsedTakeoverWarning)

a|
Risk
a|
LUN
a|
Warning
a|
LUN Latency and Node Utilization Critical Threshold Breached(ocumLunLatencyNodeUtilizationIncident)

a|
Incident
a|
LUN
a|
Critical
a|
LUN Latency and Node Utilization Warning Threshold Breached(ocumLunLatencyNodeUtilizationWarning)

a|
Risk
a|
LUN
a|
Warning
a|
QoS LUN Max IOPS Warning Threshold Breached(ocumQosLunMaxIopsWarning)

a|
Risk
a|
LUN
a|
Warning
a|
QoS LUN Max MBps Warning Threshold Breached(ocumQosLunMaxMbpsWarning)

a|
Risk
a|
LUN
a|
Warning
|===
