---
permalink: online-help/reference_save_custom_report_dialog_box.html
sidebar: sidebar
keywords: 
summary: 'You can use the Save Custom Report dialog box to save a custom report after making additional changes to the custom report.'
---
= Save Custom Report dialog box
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Save Custom Report dialog box to save a custom report after making additional changes to the custom report.

* link:reference_share_report_dialog_box_um_6_2.md#GUID-1E417C67-1F31-4FA5-AAA7-2D5BB298C6AB[reference_share_report_dialog_box_um_6_2.md#GUID-1E417C67-1F31-4FA5-AAA7-2D5BB298C6AB]
* link:reference_share_report_dialog_box_um_6_2.md#SECTION_9A2E9BA0D79549B2806F5C0F452323CB[reference_share_report_dialog_box_um_6_2.md#SECTION_9A2E9BA0D79549B2806F5C0F452323CB]

== Properties

You can save a custom report by specifying properties such as the description.

* *Report Name*
+
Displays the name of the custom report. This field cannot be edited.

* *Description*
+
Specifies the description of the customization made on the custom report. Description cannot exceed 150 characters .

== Command buttons

The command buttons enable you to perform the following tasks:

* *Save*
+
Saves the custom report .

* *Cancel*
+
Cancels the recent changes and closes the Save Custom Report dialog box.

*Related information*

xref:concept_what_reports_do.adoc[What reports do]

xref:task_editing_a_customized_report.adoc[Editing a customized report]
