---
permalink: online-help/reference-volume-relationships-inventory-report.html
sidebar: sidebar
keywords: 
summary: 'The Volume Relationships Inventory report enables you to analyze the storage inventory details in a cluster, understand the degree of protection that is required for volumes, and filter the volume details based on source of failure, pattern, and schedules.'
---
= Volume Relationships Inventory report
:icons: font
:imagesdir: ../media/

[.lead]
The Volume Relationships Inventory report enables you to analyze the storage inventory details in a cluster, understand the degree of protection that is required for volumes, and filter the volume details based on source of failure, pattern, and schedules.

The Volume Relationships Inventory report is displayed in two formats:

* SnapMirror relationships pie chart and SnapVault relationships pie chart
* Volume Relationships Inventory report tabular view

== SnapMirror and SnapVault pie charts

Displays the configuration details of the volume relationships that are present in your storage system.

== Volume Relationships Inventory tabular view

* *Relationship Health*
+
Displays the relationship heath of the cluster.

* *Relationship State*
+
Displays the the mirror state of the SnapMirror relationship.

* *Transfer Status*
+
Displays the status of the SnapMirror relationship.

* *Lag Status*
+
Displays the lag status of the volume.

* *Source Cluster*
+
Displays the name of the source cluster for the SnapMirror relationship.

* *Source SVM*
+
Displays the name of the source storage virtual machine (SVM) for the SnapMirror relationship.

* *Source Volume*
+
Displays the name of the source volume for the SnapMirror relationship.

* *Destination Cluster*
+
Displays the name of the destination cluster for the SnapMirror relationship.

* *Destination SVM*
+
Displays the name of the destination storage virtual machine (SVM) for the SnapMirror relationship.

* *Destination Volume*
+
Displays the name of the destination volume for the SnapMirror relationship.

* *Relationship Type*
+
Displays any relationship type, including SnapMirror or SnapVault.

* *Last Successful Update Time*
+
Displays the time of the last successful SnapMirror or SnapVault operation.

* *Last Transfer Duration (hrs)*
+
Displays the time taken for the last data transfer to complete.

* *Last Transfer Size (MB)*
+
Displays the size, in bytes, of the last data transfer.

* *Last Transfer End Time*
+
Displays the time that the last successful SnapMirror or SnapVault operation completed.

* *Unhealthy Reason*
+
The reason the relationship is in an unhealthy state.

* *Lag Duration (hrs)*
+
Displays the amount of time that the data on the mirror lags behind the source.

* *Version Flexible Replication*
+
Displays either Yes, Yes with backup option, or None.
