---
permalink: online-help/reference-save-custom-report-dialog-box.html
sidebar: sidebar
keywords: 
summary: 'You can use the Save Custom Report dialog box to save a custom report after making additional changes to the custom report.'
---
= Save Custom Report dialog box
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Save Custom Report dialog box to save a custom report after making additional changes to the custom report.

* link:reference-share-report-dialog-box-um-6-2.md#GUID-1E417C67-1F31-4FA5-AAA7-2D5BB298C6AB[reference-share-report-dialog-box-um-6-2.md#GUID-1E417C67-1F31-4FA5-AAA7-2D5BB298C6AB]
* link:reference-share-report-dialog-box-um-6-2.md#SECTION_9A2E9BA0D79549B2806F5C0F452323CB[reference-share-report-dialog-box-um-6-2.md#SECTION_9A2E9BA0D79549B2806F5C0F452323CB]

== Properties

You can save a custom report by specifying properties such as the description.

* *Report Name*
+
Displays the name of the custom report. This field cannot be edited.

* *Description*
+
Specifies the description of the customization made on the custom report. Description cannot exceed 150 characters .

== Command buttons

The command buttons enable you to perform the following tasks:

* *Save*
+
Saves the custom report .

* *Cancel*
+
Cancels the recent changes and closes the Save Custom Report dialog box.

*Related information*

xref:concept-what-reports-do.adoc[What reports do]

xref:task-editing-a-customized-report.adoc[Editing a customized report]
