---
permalink: online-help/reference_edit_vserver_with_infinite_volume_thresholds_dialog_box_iv.html
sidebar: sidebar
keywords: 
summary: 'You can use the Edit SVM with Infinite Volume Thresholds dialog box to modify the default threshold values of each SVM with Infinite Volume, based on your organization’s requirements. The default threshold values indicate the level of activity that must be reached on the SVM before an event is triggered.'
---
= Edit SVM with Infinite Volume Thresholds dialog box
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Edit SVM with Infinite Volume Thresholds dialog box to modify the default threshold values of each SVM with Infinite Volume, based on your organization's requirements. The default threshold values indicate the level of activity that must be reached on the SVM before an event is triggered.

== Capacity

The Capacity area enables you to set capacity threshold conditions for the selected SVM with Infinite Volume:

* *Space Nearly Full*
+
Specifies the percentage at which the SVM with Infinite Volume is considered to be nearly full. It also displays the corresponding space (in GB, MB, or TB) in the Infinite Volume. For example, if you have an Infinite Volume of size 10 GB, and the Space Nearly Full threshold is 80%, then the following information is displayed: (8 GB of 10 GB).
+
You can also use the slider to set the threshold value.

* *Space Full*
+
Specifies the percentage at which the SVM with Infinite Volume is considered full. It also displays the corresponding space (in GB, MB, or TB) in the Infinite Volume. For example, if you have an Infinite Volume of size 10 GB, and the Space Full threshold is 90%, then the following information is displayed: (9 GB of 10 GB).
+
You can also use the slider to set the threshold value.

* *Snapshot Usage Limit*
+
Specifies the limit, in percentage, of space reserved for Snapshot copies in the Infinite Volume.

== Command buttons

The command buttons enable you to perform the following tasks:

* *Restore to Global Defaults*
+
Enables you to restore the threshold settings to the current values that are set at the global level.

* *Save*
+
Saves all the threshold settings.

* *Save and Close*
+
Saves all the threshold settings and then closes the Edit SVM with Infinite Volume Thresholds dialog box.

* *Cancel*
+
Ignores any changes to the threshold settings and closes the Edit SVM with Infinite Volume Thresholds dialog box.

*Related information*

xref:task_editing_the_infinite_volume_threshold_settings.adoc[Editing the Infinite Volume threshold settings]
