---
permalink: online-help/reference-setup-autosupport-page.html
sidebar: sidebar
keywords: 
summary: 'The Setup/AutoSupport page enables you to view the AutoSupport description, enable periodic AutoSupport, or send an on-demand AutoSupport message.'
---
= Setup/AutoSupport page
:icons: font
:imagesdir: ../media/

[.lead]
The Setup/AutoSupport page enables you to view the AutoSupport description, enable periodic AutoSupport, or send an on-demand AutoSupport message.

== Information area

* *System ID*
+
Displays the system ID for this Unified Manager server.

== Periodic AutoSupport area

Enables you to have specific, predefined messages to technical support for issue diagnosis and resolution periodically generated.

* *Enable Periodic AutoSupport*
+
Indicates that you want to enable the periodic AutoSupport functionality.

== On-Demand AutoSupport area

You can generate and send an on-demand message to technical support, a specified email recipient, or both:

* *Send to Technical Support*
+
Indicates that you want to send an on-demand message to technical support for any issues that have occurred.

* *Send to Email Recipient*
+
Indicates that you want to send an on-demand message to a specified recipient for any issues that have occurred.

* *Generate and Send AutoSupport*
+
Generates and sends an on-demand message to technical support, a specified email recipient, or both for any issues that have occurred.

== HTTP Proxy area

You can designate a proxy to provide Internet access in order to send AutoSupport content to support if your environment does not provide direct access from the Unified Manager server.

* *Use HTTP proxy*
+
Check this box to identify the server being used as the HTTP proxy.
+
Enter the host name or IP address of the proxy server, and the port number used to connect to the server.

* *Use authentication*
+
Check this box if you need to provide authentication information to access the server being used as the HTTP proxy.
+
Enter the user name and the password required to authenticate with the HTTP proxy.

[NOTE]
====
HTTP proxies that provide only Basic Authentication are not supported.
====
