---
permalink: online-help/reference-edit-storage-class-thresholds-dialog-box.html
sidebar: sidebar
keywords: 
summary: 'You can use the Edit Storage Class Thresholds dialog box to modify the default threshold values of various storage classes in each SVM with Infinite Volume based on your organization’s requirements. The default threshold values indicate the level of activity that must be reached on a storage class before an event is triggered.'
---
= Edit Storage Class Thresholds dialog box
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Edit Storage Class Thresholds dialog box to modify the default threshold values of various storage classes in each SVM with Infinite Volume based on your organization's requirements. The default threshold values indicate the level of activity that must be reached on a storage class before an event is triggered.

You must have the OnCommand Administrator or Storage Administrator role.

== Capacity

The Capacity area enables you to set capacity threshold conditions for the selected storage class.

* *Space Nearly Full*
+
Specifies the percentage at which a storage class in the SVM with Infinite Volume is considered to be nearly full. It also displays the corresponding space (in GB, MB, or TB) in the storage class. For example, if you have a storage class of size 10 GB and the Space Nearly Full threshold is 80%, then the following information is displayed: (8 GB of 10 GB).
+
You can also use the slider to set the threshold value.

* *Space Full*
+
Specifies the percentage at which the storage class in the SVM with Infinite Volume is considered full. It also displays the corresponding space (in GB, MB, or TB) in the storage class. For example, if you have a storage class of size 10 GB and the Space Full threshold is 90%, then the following information is displayed: (9 GB of 10GB).
+
You can also use the slider to set the threshold value.

* *Snapshot Usage Limit*
+
Specifies the limit, in percentage, on the space reserved for Snapshot copies in the storage class.

== Command buttons

The command buttons enable you to perform tasks for a selected volume.

* *Restore to Global Defaults*
+
Enables you to restore the threshold settings to the current values that are set at the global level.

* *Save*
+
Saves all the threshold settings.

* *Save and Close*
+
Saves all the threshold settings and then closes the Edit Storage Class Thresholds dialog box.

* *Cancel*
+
Cancels changes (if any) to the threshold settings and closes the Edit Storage Class Thresholds dialog box.
