---
permalink: online-help/reference-events-report.html
sidebar: sidebar
keywords: 
summary: 'The Events report enables you to view information about event trends over a specific time period. This information enables you to compare recent activity with any past operational activity, such as configuration changes, upgrades, and so on. The information also helps you to determine any outstanding events.'
---
= Events report
:icons: font
:imagesdir: ../media/

[.lead]
The Events report enables you to view information about event trends over a specific time period. This information enables you to compare recent activity with any past operational activity, such as configuration changes, upgrades, and so on. The information also helps you to determine any outstanding events.

== Events report chart view

The Events report is displayed in two formats:

* Events report chart view
* Events report tabular view

The Events Chart is displayed in two formats:

* Events Severity Trend (All open events)
* Event Status Trend

The chart shows the event severity trends for all open events over a time period. A count of events is displayed on the vertical (y) axis and the date is displayed on the horizontal (x) axis. You can view the details for specific points on the graph by positioning your cursor over a particular point. The details display the event severity, number of events of the specific severity type, and the date of the event.

The event severity types displayed are Critical, Error, and Warning. The event severities are differentiated by different colors. There can be the same number of events on the same date in different states.

* *Count*
+
Displays a count of events.

* *Date*
+
Displays the date. The x axis shows data from the time that the event occurred up to the present date. You can click and zoom the chart to get details.

The chart shows the event status trending per day over a period of time. A count of events is displayed on the vertical (y) axis and the date is displayed on the horizontal (x) axis. The details display the event state, number of events of the specific state, and the date of the event.

The event status are New, Acknowledged, and Resolved. The event status are differentiated by different colors.

The chart shows the new events generated daily on a cumulative basis in a bar graph represented in green color. The number of Acknowledged and Resolved events are shown as and when they are acknowledged and resolved on a daily basis.

There is a zoom functionality provided within the charts. You can use this feature to zoom a particular point in the chart for more clarity.

* *Source*
+
Displays the source of an event.

* *Status*
+
Displays the severity of the event. You can filter this column to display events of a specific severity type. The event severity types are Critical, Error, or Warning.

* *State*
+
Displays the event state: New, Acknowledged, Resolved, or Obsolete. You can filter this column to show events of a specific state.

* *Event*
+
Displays the event names.

* *Triggered Time*
+
Displays the time when the event was generated. Both the time and the date are displayed.

* *Days Outstanding*
+
Displays the number of days between an event occurring and its resolution or designation as Obsolete.

* *Source Type*
+
Displays the object type (for example, Storage Virtual Machine (SVM), volume, or qtree) with which the event is associated.

* *Data Priority*
+
Displays the annotation type, based on the priority of data of the storage object.

* *Impact Level*
+
Displays whether the event is categorized as an incident, a risk, or information.

* *Impact Area*
+
Displays whether the event is a capacity, availability, performance, protection, or configuration event.

* *Assigned To*
+
Displays the name of the user to whom the event is assigned.

* *Assigned Time*
+
Displays the time when the event was assigned to a user.

* *Notes*
+
Displays the number of notes that are added for an event.

* *Acknowledged By*
+
Displays the name of the user who acknowledged the event. The field is blank if the event is not acknowledged.

* *Acknowledged Time*
+
Displays the time that has elapsed since the event was acknowledged. If the time elapsed exceeds a week, the timestamp displays when the event was acknowledged.

* *Resolved By*
+
Displays the name of the user who resolved the event. The field is blank if the event is not resolved.

* *Resolved Time*
+
Displays the time that has elapsed since the event was resolved. If the time elapsed exceeds a week, the timestamp displays when the event was resolved.

* *Obsoleted Time*
+
Displays the time when the state of the event became Obsolete.

*Related information*

xref:concept-what-health-events-are.adoc[What health events are]

xref:reference-event-management-inventory-page.adoc[Events inventory page]
