---
permalink: online-help/reference-cluster-events.html
sidebar: sidebar
keywords: 
summary: 'Cluster events provide information about the status of clusters, which enables you to monitor the clusters for potential problems. The events are grouped by impact area, and include the event name, trap name, impact level, source type, and severity.'
---
= Cluster events
:icons: font
:imagesdir: ../media/

[.lead]
Cluster events provide information about the status of clusters, which enables you to monitor the clusters for potential problems. The events are grouped by impact area, and include the event name, trap name, impact level, source type, and severity.

== Impact area: availability

An asterisk (*) identifies EMS events that have been converted to Unified Manager events.

|===
| Event name(Trap name)

| Impact level| Source type| Severity
a|
Cluster Lacks Spare Disks(ocumEvtDisksNoSpares)

a|
Risk
a|
Cluster
a|
Warning
a|
Cluster Not Reachable(ocumEvtClusterUnreachable)

a|
Risk
a|
Cluster
a|
Error
a|
Cluster Monitoring Failed(ocumEvtClusterMonitoringFailed)

a|
Risk
a|
Cluster
a|
Warning
a|
Cluster FabricPool License Capacity Limits Breached (ocumEvtExternalCapacityTierSpaceFull)

a|
Risk
a|
Cluster
a|
Warning
a|
NVMe-oF Grace Period Started *(nvmfGracePeriodStart)

a|
Risk
a|
Cluster
a|
Warning
a|
NVMe-oF Grace Period Active *(nvmfGracePeriodActive)

a|
Risk
a|
Cluster
a|
Warning
a|
NVMe-oF Grace Period Expired *(nvmfGracePeriodExpired)

a|
Risk
a|
Cluster
a|
Warning
a|
Object Maintenance Window Started(objectMaintenanceWindowStarted)

a|
Event
a|
Cluster
a|
Critical
a|
Object Maintenance Window Ended(objectMaintenanceWindowEnded)

a|
Event
a|
Cluster
a|
Information
a|
MetroCluster Spare Disks Left Behind(ocumEvtSpareDiskLeftBehind)

a|
Risk
a|
Cluster
a|
Error
a|
MetroCluster Automatic Unplanned Switchover Disabled(ocumEvtMccAutomaticUnplannedSwitchOverDisabled)

a|
Risk
a|
Cluster
a|
Warning
|===

== Impact area: capacity

|===
| Event name(Trap name)

| Impact level| Source type| Severity
a|
Cluster Cloud Tier Planning (clusterCloudTierPlanningWarning)

a|
Risk
a|
Cluster
a|
Warning
a|
FabricPool Space Nearly Full *
a|
Risk
a|
Cluster
a|
Error
|===

== Impact area: configuration

|===
| Event name(Trap name)

| Impact level| Source type| Severity
a|
Node Added(Not applicable)

a|
Event
a|
Cluster
a|
Information
a|
Node Removed(Not applicable)

a|
Event
a|
Cluster
a|
Information
a|
Cluster Removed(Not applicable)

a|
Event
a|
Cluster
a|
Information
a|
Cluster Add Failed(Not applicable)

a|
Event
a|
Cluster
a|
Error
a|
Cluster Name Changed(Not applicable)

a|
Event
a|
Cluster
a|
Information
a|
Emergency EMS received (Not applicable)

a|
Event
a|
Cluster
a|
Critical
a|
Critical EMS received (Not applicable)

a|
Event
a|
Cluster
a|
Critical
a|
Alert EMS received (Not applicable)

a|
Event
a|
Cluster
a|
Error
a|
Error EMS received (Not applicable)

a|
Event
a|
Cluster
a|
Warning
a|
Warning EMS received (Not applicable)

a|
Event
a|
Cluster
a|
Warning
a|
Debug EMS received (Not applicable)

a|
Event
a|
Cluster
a|
Warning
a|
Notice EMS received (Not applicable)

a|
Event
a|
Cluster
a|
Warning
a|
Informational EMS received (Not applicable)

a|
Event
a|
Cluster
a|
Warning
|===
ONTAP EMS events are categorized into three Unified Manager event severity levels.

|===
| Unified Manager event severity level| ONTAP EMS event severity level
a|
Critical
a|
Emergency

Critical

a|
Error
a|
Alert
a|
Warning
a|
Error

Warning

Debug

Notice

Informational

|===

== Impact area: performance

|===
| Event name(Trap name)

| Impact level| Source type| Severity
a|
Cluster IOPS Critical Threshold Breached(ocumClusterIopsIncident)

a|
Incident
a|
Cluster
a|
Critical
a|
Cluster IOPS Warning Threshold Breached(ocumClusterIopsWarning)

a|
Risk
a|
Cluster
a|
Warning
a|
Cluster MBps Critical Threshold Breached(ocumClusterMbpsIncident)

a|
Incident
a|
Cluster
a|
Critical
a|
Cluster MBps Warning Threshold Breached(ocumClusterMbpsWarning)

a|
Risk
a|
Cluster
a|
Warning
a|
Cluster Dynamic Threshold Breached(ocumClusterDynamicEventWarning)

a|
Risk
a|
Cluster
a|
Warning
|===
