---
permalink: online-help/reference-dashboards-performance-page.html
sidebar: sidebar
keywords: 
summary: 'You can use the Unified Manager Performance Dashboard to view the high-level performance status of all the clusters that are being monitored. The Dashboards/Performance page also displays a banner message when Unified Manager is unable to communicate with a cluster that it is monitoring.'
---
= Dashboards/Performance page
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Unified Manager Performance Dashboard to view the high-level performance status of all the clusters that are being monitored. The Dashboards/Performance page also displays a banner message when Unified Manager is unable to communicate with a cluster that it is monitoring.

== Overview

The clusters are ordered based on severity using the following criteria:

. If a cluster is unreachable.
. If a cluster has one or more active critical performance events (red object icon).
. If a cluster has one or more active warning performance events (yellow object icon).
. If clusters have no active performance events (green object icon): the clusters are sorted by highest IOPS.

Critical events are generated when a critical limit in a user-defined performance threshold policy is exceeded. Warning events are sent when a warning limit in a user-defined performance threshold policy is exceeded, or when a system-defined threshold policy or dynamic threshold is exceeded.

[NOTE]
====
The sort order is determined by the total number of active (new or acknowledged) events, not by the number of objects that have events. For example, if Cluster A has seven critical volume latency events, and Cluster B has two critical volume latency events and two critical node IOPS events (for a total of four critical events), Cluster A (with one red object icon) would appear higher on the list, even though Cluster B has two red object icons.
====

The following commonly monitored event types are displayed for each cluster:

* Latency events for storage virtual machines (SVMs), volumes, and LUNs
* IOPS events for nodes and SVMs
* MBps events for nodes and SVMs
* Performance capacity used events for nodes and aggregates
* Utilization events for nodes and aggregates

Unified Manager can receive performance events for other storage objects and counters--for example, MBps events for aggregates, and IOPS events for volumes. If a cluster has these types of events, the icon next to the cluster name indicates a warning (yellow) or critical (red) event. This icon might indicate that events exist when none of the five counter panel icons are yellow or red because these event types do not fit into the existing counter panel categories.

You can click the object icon to display the Performance Inventory page for that object, where you can view all objects of that type in this cluster. For example, clicking a volume icon displays the Performance/Volume Inventory page, showing a list of all the volumes in the selected cluster, sorted from worst to best performance.

== Performance counters

There are five performance counters, each displayed in a separate panel, for every cluster. This information is updated automatically after each five-minute collection period:

[options="header"]
|===
| Counter| Description
a|
Latency
a|
Shows how quickly the cluster is responding to client application requests, in milliseconds per operation (ms/op).The icon area indicates whether any SVMs, volumes, or LUNs have any active events based on the latency value crossing a threshold setting.

a|
IOPS
a|
Shows the operating speed of the storage system, in number of input/output operations per second (IOPS).

* The icon area indicates whether any nodes or SVMs have any active events based on the number of IOPS crossing a threshold setting.
* The bottom area displays the total cluster IOPS for the last five-minute collection period.

a|
MBps
a|
Shows how much data is being transferred to and from the cluster, in megabytes per second (MBps).

* The icon area indicates whether any nodes or SVMs have any active events based on the MBps value crossing a threshold setting.
* The bottom area displays the total cluster throughput for the last five-minute collection period.

a|
Performance Capacity Used
a|
Shows whether any nodes or aggregates are overusing their available performance capacity.

* The icon area indicates whether any nodes or aggregates have any active events based on the performance capacity used value crossing a threshold setting.
* The bottom area displays the highest performance capacity used value from the busiest node and busiest aggregate.

[NOTE]
====
Performance capacity data is available only when the nodes in a cluster are installed with ONTAP 9.0 or later software.
====

a|
Utilization
a|
Shows whether the resources on any nodes or aggregates are being overused.

* The icon area indicates whether any nodes or aggregates have any active events based on the utilization value crossing a threshold setting.
* The bottom area displays the highest utilization value from the busiest node and busiest aggregate.

|===
An ellipsis (...) in the header area indicates that performance data is currently being collected.

You can click *View Cluster Details* for a cluster that has performance events to display the Performance Cluster Landing page, where you can view detailed performance information about the cluster and other storage objects.

== Cluster status messages

If a cluster that is managed by Unified Manager becomes unavailable, a status message banner is displayed above the performance counters. A *Details* button is displayed at the right of the status message banner if the cluster is unreachable. By clicking the *Details* button in the status message, you can navigate to the Cluster Data Sources page, which shows complete information about the issue. On the Cluster Data Sources page, you can find the data that is required to troubleshoot the issue that made the cluster become unavailable.

*Related information*

xref:reference-description-of-event-severity-types.adoc[Description of event severity types]

xref:concept-sources-of-performance-events.adoc[Sources of performance events]

xref:concept-monitoring-cluster-performance-from-the-cluster-landing-page.adoc[Monitoring cluster performance from the Performance Cluster Landing page]

xref:concept-monitoring-performance-using-the-object-performance-inventory-pages.adoc[Monitoring performance using the Performance Inventory pages]

xref:task-displaying-information-about-a-performance-event.adoc[Displaying information about performance events]

xref:concept-managing-performance-using-perf-capacity-and-available-iops-information.adoc[Managing performance using performance capacity and available IOPS information]
