---
permalink: online-help/reference-scheduled-reports-page.html
sidebar: sidebar
keywords: 
summary: 'The Reports page enables you to view detailed information about the reports that you generate. You can search for a specific report, save a report, and delete a report. You can also schedule, share, and import a report.'
---
= Reports page
:icons: font
:imagesdir: ../media/

[.lead]
The Reports page enables you to view detailed information about the reports that you generate. You can search for a specific report, save a report, and delete a report. You can also schedule, share, and import a report.

The Reports page displays categorized groups of reports about which you can obtain specific report details. By default, the report groups expand to display the report types, a report overview, and links that enable you to customize reports. Only one report can be viewed at a time. You can click the *Run Report* button to view a report for a specific group of reports.

[NOTE]
====
The implementation of scheduling and generating reports from the Reports page will be deprecated in a future release. You can extract health and performance data from Unified Manager using these additional methods:

* Extracting data directly from the grid pages in the GUI
* Using Open Database for access to all the available objects
* Executing Unified Manager REST APIs to return the information you are interested in reviewing

====

The following is a list of report groups and report types that are displayed in the Reports page:

* Capacity Utilization Reports
 ** Storage Summary
 ** Aggregate Capacity and Utilization
 ** Volume Capacity and Utilization
 ** Qtree Capacity and Utilization
* Operational Reports - Events
* Inventory Reports
 ** Cluster Inventory
 ** NFS Exports
 ** SVM Inventory
* Imported Reports
* Data Protection Reports
 ** Volume Data Protection Configuration
 ** Volume Relationships Inventory
 ** Volume Transfer Status (Historical)
 ** Volume Transfer Rate (Historical)

*Related information*

xref:reference-cluster-capacity-fields.adoc[Storage Summary report]

xref:reference-aggregate-capacity-fields.adoc[Aggregate Capacity and Utilization report]

xref:reference-volume-capacity-fields.adoc[Volume Capacity and Utilization report]

xref:reference-qtree-capacity-fields.adoc[Qtree Capacity and Utilization report]

xref:reference-events-report.adoc[Events report]

xref:reference-cluster-health-fields.adoc[Cluster Inventory report]

xref:reference-nfs-shares-health-fields.adoc[NFS Exports report]

xref:reference-svm-health-fields.adoc[SVM Inventory report]

xref:task-exporting-storage-data-as-reports.adoc[Exporting data to CSV files for reporting]

xref:concept-unified-manager-databases-accessible-for-reporting.adoc[Unified Manager databases accessible for custom reporting]

xref:concept-using-unified-manager-rest-apis-ocum.adoc[Using Unified Manager REST APIs]
