---
permalink: online-help/reference-assign-performance-threshold-policy-page-opm.html
sidebar: sidebar
keywords: 
summary: 'You can use the Assign Threshold Policy page to assign a performance threshold policy to one or more storage objects.'
---
= Assign Performance Threshold Policy page
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Assign Threshold Policy page to assign a performance threshold policy to one or more storage objects.

The list of policies is populated with only those policies that are valid for the storage object type.

You select the that policy you want to apply to the object or objects, and then you click *Apply Policy*.

There are a few cases where an error message may be returned when you attempt to apply a policy:

* When applying a policy that uses the Performance Capacity Used counter to a node or aggregate that is not installed with ONTAP 9.0, or later, software.
+
Versions of ONTAP software prior to 9.0 do not support the performance capacity counters.

* When applying a combination policy to a FlexGroup volume, where the second counter includes either a node or aggregate object.
+
Because FlexGroup volumes can be spread across multiple nodes and aggregates, this operation is not allowed.
