---
permalink: online-help/reference_database_backup_page.html
sidebar: sidebar
keywords: 
summary: 'The Management/Database Backup page displays a list of backups created by Unified Manager and provides information about the backup name, size, creation time, and schedule.'
---
= Management/Database Backup page
:icons: font
:imagesdir: ../media/

[.lead]
The Management/Database Backup page displays a list of backups created by Unified Manager and provides information about the backup name, size, creation time, and schedule.

You must have the OnCommand Administrator or Storage Administrator role.

== Command buttons

* *Actions*
+
Displays the Database Backup Settings dialog box, which enables you to specify a backup path, retention count, and backup schedule.

== List View

The list view displays, in tabular format, information about the backups created by Unified Manager. You can use the column filters to customize the data that is displayed.

* *Name*
+
Displays the name of the selected backup.

* *Size*
+
Displays the size of the selected backup.

* *Creation Time*
+
Displays the creation date and time of the selected backup.

* *Schedule*
+
Displays the status of the backup operation. Also indicates whether it is a scheduled backup or not.
