---
permalink: online-help/reference-dashboard-page.html
sidebar: sidebar
keywords: 
summary: 'The Dashboards/Overview page displays, as a graph, the health of storage objects such as clusters, aggregates, and storage virtual machines \(SVMs\). Based on the availability, capacity, performance, and protection-related events that are generated, these storage objects are categorized as Healthy, At Risk, or Have Incidents, or as Healthy, Warning or Error for protection-related events.'
---
= Dashboards/Overview page
:icons: font
:imagesdir: ../media/

[.lead]
The Dashboards/Overview page displays, as a graph, the health of storage objects such as clusters, aggregates, and storage virtual machines (SVMs). Based on the availability, capacity, performance, and protection-related events that are generated, these storage objects are categorized as Healthy, At Risk, or Have Incidents, or as Healthy, Warning or Error for protection-related events.

== Cluster not reachable bar

When a cluster is not reachable, Unified Manager displays the details in a bar at the top of every page. If all clusters are reachable, this pane is hidden.

You can refresh the information displayed in the pane by pressing F5. This action ensures that the pane displays the latest information about clusters that are currently not reachable. For example, if a cluster with a Cluster Not Reachable event is removed or if the state of an event is Obsolete, information about the event is removed when you refresh the pane.

You can view detailed information about a cluster that is unreachable by clicking the *Details* button. This action opens the Events inventory page. After the bar is closed, it is displayed again only when you log back in to Unified Manager.

== Overview area

* *Availability pane*
+
Displays information about the availability of clusters, aggregates, and SVMs that are monitored by Unified Manager. The storage objects are categorized as Healthy, At Risk, or Have Incidents. For example, the status of a cluster that lacks spare disks is displayed as At Risk.
+
This pane also displays the number of storage objects in each of the categories. Clicking on any of the object totals takes you to the page for that object. For example, clicking the cluster total takes you to the Health/Clusters inventory page. Clicking on the numbers at the top of a column takes you to the Events inventory page.

* *Capacity pane*
+
Displays information about the capacity of aggregates and SVMs that are monitored by Unified Manager. The storage objects are categorized as Healthy, At Risk, or Have Incidents. For example, the status of an aggregate whose used capacity has reached the full threshold value is displayed as At Risk.
+
This pane also displays the number of storage objects in each of the categories.

* *Performance pane*
+
Displays information about the performance of clusters, SVMs, and volumes that are monitored by Unified Manager. Based on the performance-related incidents that are generated, the storage objects are categorized as Healthy, At Risk, or Have Incidents. For example, the status of a volume whose I/O response time to its workload has reached the maximum threshold value is displayed as Have Incidents.
+
This pane also displays the total number of clusters, SVMs, and volumes that are monitored by Unified Manager. Clicking on any of the object totals takes you to the page for that object. For example, clicking the cluster total takes you to the Performance/Cluster inventory page.

* *Protection pane*
+
Displays information about protection relationships that are monitored by Unified Manager. The protection relationships are categorized as Healthy, Warning, or Error. For example, a relationship that has a lag duration that exceeds the lag warning threshold is displayed as Warning.
+
This pane also displays the total number of storage objects in each of the protection categories. Clicking the links for the Lag Status, Asynchronous Vault, Asynchronous Mirror, or Synchronous categories takes you to a filtered list of those objects in the Protection/Volume Relationships page.

*Related information*

xref:concept-what-health-events-are.adoc[What health events are]

xref:reference-performance-event-analysis-and-notification.adoc[Performance event analysis and notification]

xref:reference-dashboards-performance-page.adoc[Dashboards/Performance page]

xref:reference-dashboards-cluster-view-page.adoc[Dashboards/Cluster View page]
