---
permalink: online-help/reference_performance_statistics_displayed_in_the_data_breakdown_charts.html
sidebar: sidebar
keywords: 
summary: 'You can use the graphs to view performance trending for a volume. You can also view statistics for reads and writes, network protocol activity, the impact of QoS policy group throttling on latency, the ratio of reads and writes to cache storage, the total cluster CPU time used by a workload, and specific cluster components.'
---
= Performance statistics displayed in the data breakdown charts
:icons: font
:imagesdir: ../media/

[.lead]
You can use the graphs to view performance trending for a volume. You can also view statistics for reads and writes, network protocol activity, the impact of QoS policy group throttling on latency, the ratio of reads and writes to cache storage, the total cluster CPU time used by a workload, and specific cluster components.

These views display a maximum of 30 days of statistics from the current day. On the historic data chart, if you select a time frame of more than 1 day, depending on your screen resolution, the charts display the maximum values for latency and IOPS across the number of days.

[NOTE]
====
You can use the *Select All* check box to select, or deselect, all the listed chart options.
====

* *Latency*
+
The following charts detail the latency, or response time, information for the selected workload:

 ** *Cluster Components*
+
Displays a graph of the time spent at each cluster component used by the selected volume.
+
The chart helps you determine the latency impact by each component as it relates to the total latency. You can use the check box next to each component to show and hide its graph.
+
For QoS policy groups, data is only displayed for user-defined policy groups. Zeros are displayed for system-defined policy groups, such as default policy groups.

 ** *Reads/writes latency*
+
Displays a graph of the latencies of the successful read and write requests from the selected volume workload over the selected time frame.
+
Write requests are an orange line and read requests are a blue line. The requests are specific to the latency for the selected volume workload, not all workloads on the cluster.
+
[NOTE]
====
The read and write statistics might not always add up to the total latency statistics displayed in the Latency chart. This is expected behavior based on how Unified Manager collects and analyzes read and write statistics for a workload.
====

 ** *Policy Group Impact*
+
Displays a graph of the percentage of the latency for the selected volume workload that is impacted by the throughput limit on its QoS policy group.
+
If the workload is throttled, the percentage indicates how much the throttling contributed to the latency at a specific point in time. The percentage values indicate the amount of throttling:

  *** 0% = no throttling
  *** > 0% = throttling
  *** > 20% = critical throttling
If the cluster can handle more work, you can reduce throttling by increasing the policy group limit. Another option is to move the workload to a less busy aggregate.

+
[NOTE]
====
The chart displays for workloads in a user-defined QoS policy group with a set throughput limit only. It does not display if the workloads are in a system-defined policy group, such as the default policy group, or a policy group that does not have a QoS limit. For a QoS policy group, you can point the cursor to the name of the policy group to display its throughput limit and the last time it was modified. If the policy group was modified before the associated cluster was added to Unified Manager, the last modified time is the date and time when Unified Manager first discovered the cluster.
====

* *IOPS*
+
The following charts detail the IOPS data for the selected workload:

 ** *Reads/writes/other*
+
Displays a graph showing the number of read and write IOPS and other IOPS, per second, over the selected time frame.
+
Other IOPS are protocol activities initiated by the client that are not reads or writes. For example, in an NFS environment, this could be metadata operations such as getattr, setattr, or fsstat. In a CIFS environment, this could be attribute lookups, directory listings, or antivirus scans. Write IOPS are an orange line and read requests are a blue line. The requests are specific to all operations for the selected volume workload, not all operations on the cluster.

* *MBps*
+
The following charts detail the throughput data for the selected workload:

 ** *Cache hit ratio*
+
Displays a graph of the percentage of read requests from client applications satisfied by cache over the selected time frame.
+
The cache could be on Flash Cache cards or solid state drives (SSDs) in Flash Pool aggregates. A cache hit, in blue, is a read from cache. A cache miss, in orange, is a read from a disk in the aggregate. The requests are specific to the selected volume workload, not all workloads on the cluster.
+
You can view more detailed information about volume cache usage in the Unified Manager Health pages and in OnCommand System Manager.

* *Components*
+
The following charts detail the data by cluster component used by the selected workload:

 ** *Cluster CPU Time*
+
Displays a graph of the CPU usage time, in ms, for all nodes in the cluster used by the selected workload.
+
The graph displays the combined CPU usage time for network processing and data processing. The CPU time for system-defined workloads that are associated to the selected workload, and are using the same nodes for data processing, is also included. You can use the chart to determine whether the workload is a high consumer of the CPU resources on the cluster. You can also use the chart, in combination with the Reads/writes latency chart under the Latency chart, or the Reads/writes/other chart under the IOPS chart, to determine how changes to workload activity over time impact cluster CPU utilization.

 ** *Disk Utilization*
+
Displays a graph showing the percentage of utilization on the data disks in the storage aggregate over the selected time frame.
+
The utilization includes disk read and write requests from the selected volume workload only. Reads from cache are not included. The utilization is specific to the selected volume workload, not all workloads on the disks. If a monitored volume is involved in a volume move, the utilization values in this chart are for the target aggregate to which the volume moved.
