---
permalink: online-help/reference-create-storage-virtual-machine-associations-wizard.html
sidebar: sidebar
keywords: 
summary: 'The Create Storage Virtual Machine Associations wizard enables you to associate source and destination storage virtual machines \(SVMs\) for use in SnapMirror and SnapVault protection relationships.'
---
= Create Storage Virtual Machine Associations wizard
:icons: font
:imagesdir: ../media/

[.lead]
The Create Storage Virtual Machine Associations wizard enables you to associate source and destination storage virtual machines (SVMs) for use in SnapMirror and SnapVault protection relationships.

== Select Source SVM

The Select Source Storage Virtual Machine panel enables you to select the source, or primary, SVM in the SVM association.

* *Any*
+
Enables you to create an association between any SVM source to one or more destination, or secondary, SVM. This means that all existing SVMs that currently require protection, as well as any SVMs that are created in the future, are associated with the specified destination SVM. For example, you might want applications from several different sources at different locations backed up to one or more destination SVM in one location.

* *Single*
+
Enables you to associate a specific source SVM with one or more destination SVMs. For example, if you are providing storage services to many clients whose data must be separate from one another, choose this option to associate a specific SVM source to a specific SVM destination that is assigned only to that client.

* *None (External)*
+
Enables you to create an association between a source SVM and an external flexible volume of a destination SVM.

 ** Storage Virtual Machine
+
Lists the names of the available source SVMs

 ** Cluster
+
Lists the clusters on which each SVM resides

* *Allow these kinds of relationships*
+
Enables you to select the relationship type for the association:

 ** SnapMirror
+
Specifies a SnapMirror relationship as the association type. Selecting this option enables data replication from the selected sources to the selected destinations.

 ** SnapVault
+
Specifies a SnapVault relationship as the association type. Selecting this option enables backups from the selected primary locations to the selected secondary locations.

== Select Protection Destinations

The Select Protection Destinations panel of the Create Storage Virtual Machine Associations wizard enables you to select where to copy or replicate the data. You can create an association on only one destination SVM per cluster.

== Command buttons

The command buttons enable you to perform the following tasks:

* *Next*
+
Advances you to the next page in the wizard.

* *Back*
+
Returns you to the previous page in the wizard.

* *Finish*
+
Applies your selections and creates the association.

* *Cancel*
+
Discards the selections and closes the Create Storage Virtual Machine Associations wizard.
