---
permalink: online-help/reference_relationship_last_1_month_transfer_status_view.html
sidebar: sidebar
keywords: 
summary: 'The Protection/Volume Transfer Status \(Historical\) page enables you to analyze the volume transfer trends over a period of time. This page also displays whether the volume transfer was a success or a failure.'
---
= Protection/Volume Transfer Status (Historical) page
:icons: font
:imagesdir: ../media/

[.lead]
The Protection/Volume Transfer Status (Historical) page enables you to analyze the volume transfer trends over a period of time. This page also displays whether the volume transfer was a success or a failure.

Use the *Export* button to export the details of all the monitored volumes to a comma-separated values (`.csv`) file.

[NOTE]
====
This page displays information for volumes in asynchronous relationships only - volumes in synchronous relationships are not shown.
====

* *Source Cluster*
+
Displays the source cluster name.

* *Source SVM*
+
Displays the storage virtual machine (SVM) name.

* *Source Volume*
+
Displays the source volume name.

* *Destination Cluster*
+
Displays the destination cluster name.

* *Destination SVM*
+
Displays the destination SVM name.

* *Destination Volume*
+
Displays the destination volume name.

* *Operation Result*
+
Displays whether volume transfer was successful.

* *Transfer Start Time*
+
Displays the volume transfer start time.

* *Transfer End Time*
+
Displays the volume transfer end time.

* *Transfer Duration*
+
Displays the time taken (in hours) to complete the volume transfer.

* *Transfer Size*
+
Displays the size (in MB) of the transferred volume.

* *Operation Type*
+
Displays the type of volume transfer.
