---
permalink: online-help/reference-relationship-last-1-month-transfer-rate-view.html
sidebar: sidebar
keywords: 
summary: 'The Protection/Volume Transfer Rate \(Historical\) page enables you to analyze the amount of data volume that is transferred on a day-to-day basis. This page also provides details about daily volume transfers and the time required to complete the transfer operation.'
---
= Protection/Volume Transfer Rate (Historical) page
:icons: font
:imagesdir: ../media/

[.lead]
The Protection/Volume Transfer Rate (Historical) page enables you to analyze the amount of data volume that is transferred on a day-to-day basis. This page also provides details about daily volume transfers and the time required to complete the transfer operation.

Use the *Export* button to export the details of all the monitored volumes to a comma-separated values (`.csv`) file.

[NOTE]
====
This page displays information for volumes in asynchronous relationships only - volumes in synchronous relationships are not shown.
====

* *Total Transfer Size*
+
Displays the total size of the volume transfer in gigabytes.

* *Day*
+
Displays the day on which the volume transfer was initiated.

* *End Time*
+
Displays the volume transfer end time with date.
