---
permalink: online-help/reference-nfs-shares-health-fields.html
sidebar: sidebar
keywords: 
summary: 'NFS Exports report enables you to audit information about NFS export policies and its associated rules for volumes in your storage system.'
---
= NFS Exports report
:icons: font
:imagesdir: ../media/

[.lead]
NFS Exports report enables you to audit information about NFS export policies and its associated rules for volumes in your storage system.

== NFS Exports report tabular view

* *Cluster*
+
Displays the name of the cluster.

* *Storage Virtual Machine*
+
Displays the name of the SVM with NFS export policies.

* *Volume*
+
Displays the name of the volume with NFS export policies.

* *Qtree*
+
Displays the name of the qtree on a volume with NFS export policies.

* *Volume State*
+
Displays the current state of the volume. The state can be Offline, Online, or Restricted.

 ** Offline
+
Read or write access to the volume is not allowed.

 ** Online
+
Read and write access to the volume is allowed.

 ** Restricted
+
Limited operations, such as parity reconstruction, are allowed, but data access is not allowed.

* *Junction Path*
+
Displays the path on which the volume is mounted.

* *Junction Path Active*
+
Displays whether the path to access the mounted volume is active or inactive.

* *Export policy*
+
Displays the rules that define the access permission for volumes that are exported.

* *Rule Index*
+
Displays the rules associated with the export policy such as the authentication protocols and the access permission.

* *Access Protocols*
+
Displays the protocols that are enabled for the export policy rules.

* *Client Match*
+
Displays the clients that have permission to access data on the volumes.

* *Read Only Access*
+
Displays the authentication protocol used to read data on the volumes.

* *Read Write Access*
+
Displays the authentication protocol used to read or write data on the volumes.

* *Security Style*
+
Displays the access permission for volumes that are exported. The security style can be UNIX, Unified, NTFS, or Mixed.

 ** UNIX (NFS clients)
+
Files and directories in the volume have UNIX permissions.

 ** Unified
+
Files and directories in the volume have a unified security style.

 ** NTFS (CIFS clients)
+
Files and directories in the volume have Windows NTFS permissions.

 ** Mixed
+
Files and directories in the volume can have either UNIX permissions or Windows NTFS permissions.

* *Unix Permission*
+
Displays the UNIX permission bits in an octal string format, which is set for the volumes that are exported. It is similar to the UNIX style permission bits.
