---
permalink: online-help/reference-save-customized-report-as-dialog-box.html
sidebar: sidebar
keywords: 
summary: 'You can use the Save Customized Report As dialog box to save a report after customizing it.'
---
= Save Customized Report As dialog box
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Save Customized Report As dialog box to save a report after customizing it.

* link:reference-share-report-dialog-box-um-6-2.md#GUID-1E417C67-1F31-4FA5-AAA7-2D5BB298C6AB[reference-share-report-dialog-box-um-6-2.md#GUID-1E417C67-1F31-4FA5-AAA7-2D5BB298C6AB]
* link:reference-share-report-dialog-box-um-6-2.md#SECTION_9A2E9BA0D79549B2806F5C0F452323CB[reference-share-report-dialog-box-um-6-2.md#SECTION_9A2E9BA0D79549B2806F5C0F452323CB]

== Properties

You can customize and save a report by specifying properties such as the name and description.

* *Report Name*
+
Displays the name of the report. The original report name is displayed by default. You can modify the report name as per the customization. Report name cannot exceed 255 characters.

* *Description*
+
Specifies the description of the customization made on the report. Description cannot exceed 150 characters.

== Command buttons

The command buttons enable you to perform the following tasks:

* *Save*
+
Saves the customized report .

* *Cancel*
+
Cancels the recent changes and closes the Save Customized Report As dialog box.

*Related information*

xref:concept-what-reports-do.adoc[What reports do]

xref:task-customizing-a-report.adoc[Customizing a report]
