---
permalink: online-help/reference-volume-transfer-rate-historical-report.html
sidebar: sidebar
keywords: 
summary: 'The Volume Transfer Rate \(Historical\) report enables you to analyze the amount of data volume that is transferred on a day-to-day basis. The report also provides details about daily volume transfers and the time required to complete the transfer operation.'
---
= Volume Transfer Rate (Historical) report
:icons: font
:imagesdir: ../media/

[.lead]
The Volume Transfer Rate (Historical) report enables you to analyze the amount of data volume that is transferred on a day-to-day basis. The report also provides details about daily volume transfers and the time required to complete the transfer operation.

The Volume Transfer Rate (Historical) report is displayed in two formats:

* Volume Transfer Rate bar chart
* Volume Transfer Rate tabular view

== Volume Transfer Rate bar chart

Displays the volume transfer rate details by plotting the total transfer size against the number of hours. You can also view the details of the amount of data that is transferred on a daily basis.

== Volume Transfer Rate tabular view

* *Total Transfer Size (GB)*
+
Displays the total size of the volume transfer in gigabytes.

* *Day*
+
Displays the day on which the volume transfer was initiated.

* *End Time*
+
Displays the volume transfer end time with date.
