---
permalink: online-help/reference-capacity-all-volumes-view.html
sidebar: sidebar
keywords: 
summary: 'The Health/Volumes Capacity and Utilization page enables you to view information about the capacity and utilization of volumes in a cluster. This information enables you to understand possible capacity risks and to view the configured, used, and unused capacity of volumes. Also, the information helps you to make decisions about enabling space-saving features such as deduplication and thin provisioning.'
---
= Health/Volumes Capacity and Utilization page
:icons: font
:imagesdir: ../media/

[.lead]
The Health/Volumes Capacity and Utilization page enables you to view information about the capacity and utilization of volumes in a cluster. This information enables you to understand possible capacity risks and to view the configured, used, and unused capacity of volumes. Also, the information helps you to make decisions about enabling space-saving features such as deduplication and thin provisioning.

Use the *Export* button to export the details of all the monitored volumes to a comma-separated values (`.csv`) file.

* *Cluster*
+
The cluster name.

* *SVM*
+
The name of the storage virtual machine (SVM) that contains the volume.

* *Volume*
+
The volume name.

* *Total Data Capacity*
+
The total data capacity (used plus available) in a volume.

* *Used Data Capacity*
+
The used data capacity in a volume.

* *Used Data %*
+
The used data in a volume as a percentage.

* *Available Data Capacity*
+
The available data capacity in a volume.

* *Available Data %*
+
The available data capacity in a volume as a percentage.

* *Daily Growth Rate %*
+
The growth rate that occurs every 24 hours in the volume.

* *Days To Full*
+
The estimated number of days remaining before the volume reaches full capacity.

* *Space Full Threshold %*
+
The percentage of space used in the volume that is considered full.

* *Space Nearly Full Threshold %*
+
The percentage of space used in the volume that is considered nearly full.

* *Growth Rate Threshold %*
+
The volume's growth rate that is considered to be normal before the system generates a Volume Growth Rate Abnormal event.

* *Growth Rate Sensitivity Threshold*
+
The factor that is applied to the standard deviation of a volume's growth rate. If the growth rate exceeds the factored standard deviation, a Volume Growth Rate Abnormal event is generated.

* *Days Until Full Threshold*
+
The number of days remaining before reaching full capacity.

* *Snapshot Overflow %*
+
The percentage of the data space that is consumed by Snapshot copies.

* *Snapshot Reserve Used Capacity*
+
The amount of space used by Snapshot copies in the volume.

* *Snapshot Reserve Used %*
+
The amount of space used by Snapshot copies in the volume as a percentage.

* *Snapshot Reserve Available Capacity*
+
The amount of space available for Snapshot copies in the volume.

* *Snapshot Reserve Available %*
+
The amount of space available for Snapshot copies in the volume as a percentage.

* *Snapshot Reserve Total Capacity*
+
Displays the total Snapshot copy capacity in the volume.

* *Snapshot Copies Reserve Full Threshold %*
+
The percentage at which the space reserved for Snapshot copies is considered full.

* *Snapshot Copies Count Threshold*
+
The number of Snapshot copies on a volume that are considered to be too many.

* *Snapshot Copies Days Until Full Threshold*
+
The number of days remaining before the space reserved for Snapshot copies reaches full capacity.

* *Number Of Inodes*
+
The number of inodes in the volume.

* *Inode Utilization %*
+
The percentage of inode space used in the volume.

* *Inodes Full Threshold %*
+
The percentage at which a volume is considered to have consumed all of its inodes.

* *Inodes Nearly Full Threshold %*
+
The percentage at which a volume is considered to have consumed most of its inodes.

* *Quota Committed Capacity*
+
The space reserved for quotas in the volume.

* *Quota Overcommitted Capacity*
+
The amount of space that can be used for quotas before the system generates the Volume Quota Overcommitted event.

* *Quota Overcommitted Threshold %*
+
The percentage at which the space used for quotas on the volume is considered overcommitted.

* *Quota Nearly Overcommitted Threshold %*
+
The percentage at which the space used for quotas on the volume is considered nearly overcommitted.

* *Snapshot Autodelete*
+
Whether automatic deletion of Snapshot copies is enabled or disabled.

* *Deduplication*
+
Whether deduplication is enabled or disabled for the volume.

* *Deduplication Space Savings*
+
The amount of space saved in a volume by using deduplication.

* *Compression*
+
Whether compression is enabled or disabled for the volume.

* *Compression Space Savings*
+
The amount of space saved in a volume by using compression.

* *Caching Policy*
+
The caching policy that is associated with the selected volume.
+
The policy provides information about how Flash Pool caching occurs for the volume. See the Health/Volumes inventory page for more information on caching policies.

* *Cache Retention Priority*
+
The priority used for retaining cached pools.

* *Thin Provisioned*
+
Whether space guarantee is set for the selected volume. Valid values are Yes and No.

* *Autogrow*
+
Whether the volume automatically grows in size when it is out of space.

* *Space Guarantee*
+
The storage guarantee option that is associated with the volume.

* *Protection Role*
+
The protection role that is set for the volume.

* *State*
+
The state of the volume that is being exported.

* *SnapLock Type*
+
Whether the volume is a SnapLock or non-SnapLock volume.

* *SnapLock Expiry Date*
+
The SnapLock expiration date.

* *Tiering Policy*
+
The tiering policy set for the volume. Valid when deployed on FabricPool-enabled aggregates only.

*Related information*

xref:task-viewing-the-volume-list-and-details.adoc[Viewing the volume list and details]
