---
permalink: online-help/reference-event-retention-settings-dialog-box.html
sidebar: sidebar
keywords: 
summary: 'You can configure the event settings to automatically delete events \(information, resolved, or obsolete\) after a specified time and at a specified frequency. You can also delete these events manually.'
---
= Event Retention Settings dialog box
:icons: font
:imagesdir: ../media/

[.lead]
You can configure the event settings to automatically delete events (information, resolved, or obsolete) after a specified time and at a specified frequency. You can also delete these events manually.

You must have the OnCommand Administrator or Storage Administrator role.

== Event Settings

You can configure the following options:

* *Delete Information, Resolved, and Obsolete Events Older Than*
+
Enables you to specify the retention period after which events that are marked as Information, Resolved, or Obsolete are removed from the management server.
+
The default value is 180 days. Retaining the events for more than 180 days affects the performance and is not recommended. The lower limit for the event retention period is 7 days, although there is no upper limit.

* *Delete Schedule*
+
Enables you to specify the frequency at which all the events that are marked as Information, Resolved, or Obsolete and that have exceeded their age limit are automatically deleted from the management server. The possible values are Daily, Weekly, or Monthly.
+
The default value is Daily.

* *Delete Now*
+
Enables you to manually delete all the information, resolved, and obsolete events that have exceeded their specified retention period.

== Command buttons

The command buttons enable you to save or cancel the setup options:

* *Save and Close*
+
Saves the configuration settings for the selected option and closes the dialog box.

* *Cancel*
+
Cancels the recent changes and closes the dialog box.

*Related information*

xref:task-configuring-event-retention-settings.adoc[Configuring event retention settings]
