---
permalink: online-help/reference-cluster-capacity-fields.html
sidebar: sidebar
keywords: 
summary: 'The Storage Summary report enables you to view summarized information about storage capacity in the HA pairs. This information helps you to understand possible capacity risks and to take appropriate action to rebalance workload. Single-node cluster information is not visible in the report.'
---
= Storage Summary report
:icons: font
:imagesdir: ../media/

[.lead]
The Storage Summary report enables you to view summarized information about storage capacity in the HA pairs. This information helps you to understand possible capacity risks and to take appropriate action to rebalance workload. Single-node cluster information is not visible in the report.

== Storage Summary report chart view

The Storage Summary report is displayed in two formats:

* Storage Summary report chart view
* Storage Summary report tabular view

The chart shows the capacity trend of used and unused data capacity of the aggregates over a period of time. Total data capacity is displayed on the vertical (y) axis and the cluster name on the horizontal (x) axis. Therefore, each bar in the chart represents one cluster. You can view the details for specific points on the graph by positioning your cursor over a particular point.

* *Cluster Name*
+
Displays the cluster name.

* *HA Pair*
+
Displays the HA pair value obtained by forming two nodes.

* *Model*
+
Displays the name of the model.

* *OS Version*
+
Displays the version of ONTAP used.

* *Total Raw Capacity*
+
Displays the total physical capacity of all disks in the array.

* *Unconfigured Raw Capacity*
+
Displays the unconfigured capacity of disks whose container type is other than aggregate, broken, spare, or shared. This capacity is always higher than the physical capacity of the disk in ONTAP. For example, consider a 2 TB disk. The physical capacity of the disk is 1.6 TB in ONTAP whereas the unconfigured raw capacity in Unified Manager is 1.8 TB.

* *Aggregate Total Capacity*
+
Displays the total size of the available aggregates for the user. This includes the Snapshot copy reserve.

* *Aggregate Used Capacity*
+
Displays the capacity already in use on aggregates. This includes the capacity consumed by volumes, LUNs, and other storage efficiency technology overheads.

* *Aggregate Unused Capacity*
+
Displays capacity that might be available for storing additional data on the aggregate. This includes the Snapshot copy reserve.

* *Allocated LUN Capacity*
+
Displays the capacity of LUNs that are mapped.

* *Unallocated LUN Capacity*
+
Displays the capacity of all LUNs not mapped to the Host.

* *Volume Total Capacity*
+
Displays the total capacity of the volumes (used plus unused).

* *Volume Used Capacity*
+
Displays the used capacity of the volumes.

* *Volume Unused Capacity*
+
Displays the unused capacity of the volumes.

* *Volume Protection Capacity*
+
Displays the capacity of volumes that have SnapMirror and SnapVault enabled.

* *Cluster Licensed Cloud Tier Total*
+
Displays the total capacity that has been licensed in the cloud tier. This field is displayed for storage providers that require a FabricPool license, for example, Amazon S3, IBM Cloud Object Storage, Microsoft Azure Cloud, or Alibaba Cloud Object Storage.

* *Cluster Licensed Cloud Tier Used*
+
Displays the space used by data in the cloud tier for storage providers that require a FabricPool license.

* *Cluster StorageGRID Capacity Used*
+
Displays the space used by data in the cloud tier for storage providers that do not require a FabricPool license, for example, StorageGRID.

*Related information*

xref:concept-managing-and-monitoring-clusters-and-cluster-object-health.adoc[Managing and monitoring clusters and cluster object health]
