---
permalink: online-help/reference_share_report_dialog_box_um_6_2.html
sidebar: sidebar
keywords: 
summary: 'You can share a report with one or more users through email. After you customize a report, you must save the changes before you share the report to ensure that the changes are displayed.'
---
= Share Report dialog box
:icons: font
:imagesdir: ../media/

[.lead]
You can share a report with one or more users through email. After you customize a report, you must save the changes before you share the report to ensure that the changes are displayed.

* <<GUID-1E417C67-1F31-4FA5-AAA7-2D5BB298C6AB,#GUID-1E417C67-1F31-4FA5-AAA7-2D5BB298C6AB>>
* <<SECTION_9A2E9BA0D79549B2806F5C0F452323CB,#SECTION_9A2E9BA0D79549B2806F5C0F452323CB>>

== Properties

You can share a report by specifying properties such as the email address of the user, subject of the email, and the format of the report.

* *Recipient Email Address*
+
Specifies the email address of the user with whom you want to share the report. You can specify one or more entries, separated by commas. This is a mandatory field.

* *Subject*
+
Specifies the subject of the email. By default, the name of the report is displayed.

* *Report Format*
+
Specifies the format in which you want to share the report. The _PDF_ option is selected by default. If the XHTML format is selected, open the report that is sent by email by using a supported web browser.

== Command buttons

The command buttons enable you to perform the following tasks:

* *Share*
+
Shares the report with the saved configuration and closes the Share Report dialog box.

* *Cancel*
+
Closes the Share Report dialog box while displaying a message to save the report configuration.

*Related information*

xref:concept_what_report_sharing_is.adoc[What report sharing is]

xref:task_sharing_reports.adoc[Sharing reports]
