---
permalink: online-help/task-exporting-a-data-policy-configuration.html
sidebar: sidebar
keywords: 
summary: 'You can export a data policy configuration from Unified Manager to a file. For example, after you have taken the required backup, and in the event of a disaster, you can export the data policy configuration from the primary.'
---
= Exporting a data policy configuration
:icons: font
:imagesdir: ../media/

[.lead]
You can export a data policy configuration from Unified Manager to a file. For example, after you have taken the required backup, and in the event of a disaster, you can export the data policy configuration from the primary.

== Before you begin

You must have the OnCommand Administrator or Storage Administrator role.

== About this task

The Data Policy tab, which is used while performing this task, is displayed only for SVMs with Infinite Volume.

== Steps

. In the left navigation pane, click *Health* > *SVMs*.
. In the *Health/Storage Virtual Machines* inventory page, select the appropriate SVM.
. Click *Data Policy*.
+
The list of rules in the data policy for the selected SVM with Infinite Volume is displayed.

. Click *Export*.
. In the browser-specific dialog box, specify the location to which the data policy configuration has to be exported.

== Results

The data policy configuration is exported as a JSON file in the specified location.
