---
permalink: online-help/task-viewing-the-aggregate-list-and-details.html
sidebar: sidebar
keywords: 
summary: 'From the Health/Aggregates inventory page, you can monitor your inventory of aggregates. The Health/Aggregates Capacity and Utilization page enables you to view information about the capacity and utilization of aggregates in all clusters.'
---
= Viewing the aggregate list and details
:icons: font
:imagesdir: ../media/

[.lead]
From the Health/Aggregates inventory page, you can monitor your inventory of aggregates. The Health/Aggregates Capacity and Utilization page enables you to view information about the capacity and utilization of aggregates in all clusters.

== Before you begin

You must have the Operator, OnCommand Administrator, or Storage Administrator role.

== About this task

You can view details such as aggregate capacity and configuration, and disk information from the Health/Aggregate details page. You can use these details before you configure the threshold settings if required.

== Steps

. In the left navigation pane, click *Health* > *Aggregates*.
. Choose one of the following ways to view the aggregate details:
 ** To view information about the capacity and utilization of all aggregates in all clusters, in the View menu, select *Aggregate Capacity and Utilization*.
 ** To view minimal details, position the cursor over the aggregate name.
 ** To view the complete details, click the aggregate name.
+
You can also view the complete details by clicking *View Details* in the minimal details dialog box.
. View the objects related to the aggregate by clicking *View Related* from the minimal details dialog box.
