---
permalink: online-help/task_restoring_a_mysql_database_backup_on_red_hat_enterprise_linux_or_centos.html
sidebar: sidebar
keywords: Unified Manager
summary: 'If data loss or data corruption occurs, you can restore Unified Manager to the previous stable state with minimum loss of data. You can restore the Unified Manager database to a local or remote Red Hat Enterprise Linux or CentOS system.'
---
= Restoring a database backup on a Linux system
:icons: font
:imagesdir: ../media/

[.lead]
If data loss or data corruption occurs, you can restore Unified Manager to the previous stable state with minimum loss of data. You can restore the Unified Manager database to a local or remote Red Hat Enterprise Linux or CentOS system.

== Before you begin

* You must have Unified Manager installed on a server.
* You must have the root user credentials for the Linux host on which Unified Manager is installed.
* You must have copied the Unified Manager backup file and the contents of the database repository directory to the system on which you will perform the restore operation.
+
It is recommended that you copy the backup file to the default directory `/data/ocum-backup`. The database repository files must be copied to the `/database-dumps-repo` subdirectory under the `/ocum-backup` directory.

* The backup files must be of `.7z` type.

== About this task

The restore feature is platform-specific and version-specific. You can restore a Unified Manager backup only on the same version of Unified Manager. You can restore a Linux backup file or a virtual appliance backup file to a Red Hat Enterprise Linux or CentOS system.

[TIP]
====
If the backup folder name contains a space, you must include the absolute path or relative path in double quotation marks.
====

== Steps

. If you are performing a restore onto a new server, after installing Unified Manager do not launch the UI or configure any clusters, users, or authentication settings when the installation is complete. The backup file populates this information during the restore process.
. Log in as the root user to the host on which Unified Manager is installed.
. If Unified Manager is installed in VCS setup, then stop the Unified Manager ocie and ocieau services using Veritas Operations Manager.
. At the command prompt, restore the backup: `um backup restore -f <backup_file_path>/<backup_file_name>`
+
`um backup restore -f /data/ocum-backup/UM_9.4.N151113.1348_backup_rhel_02-20-2018-04-45.7z`

== After you finish

After the restore operation is complete, you can log in to Unified Manager.

*Related information*

xref:concept_what_a_database_restore_is.adoc[What a database restore is]
