---
permalink: online-help/task-troubleshooting-non-availability-of-cifs-shares.html
sidebar: sidebar
keywords: 
summary: 'You might not be able to access CIFS shares if the storage objects serving these shares are unavailable. You should review availability events such as Volume Offline, Junction Path Offline, or SVM CIFS Server Down that are generated when these objects are unavailable.'
---
= Troubleshooting access to CIFS shares
:icons: font
:imagesdir: ../media/

[.lead]
You might not be able to access CIFS shares if the storage objects serving these shares are unavailable. You should review availability events such as Volume Offline, Junction Path Offline, or SVM CIFS Server Down that are generated when these objects are unavailable.

== Before you begin

You must have the role of Storage Administrator to perform this task.

== About this task

If you have configured an appropriate alert, you will be notified about the availability event through an alert email.

== Steps

. In the *Dashboards/Overview* page, click the appropriate offline event.
+
For example, if you receive a Volume Offline event, click the *`Volume_name` Volume Offline* event in the Availability panel in the Unresolved Incidents and Risks area.

. In the *Event* details page, click *`Volume_name`* in the *Source* field.
. In the *Health/Volume* details page, click the number corresponding to CIFS Shares in the *Related Devices* pane.
. In the *Health/Storage Virtual Machine* details page, click the *CIFS Shares* tab.
+
You can view the number of CIFS shares that are affected.

== After you finish

You must resolve the failures by using either OnCommand System Manager or the ONTAP CLI.
