---
permalink: online-help/task-configuring-global-volume-health-threshold-values.html
sidebar: sidebar
keywords: 
summary: 'You can configure the global health threshold values for all volumes to track any threshold breach. Appropriate events are generated for health threshold breaches, and you can take preventive measures based on these events. You can configure the global values based on the best practice settings for thresholds that apply to all monitored volumes.'
---
= Configuring global volume health threshold values
:icons: font
:imagesdir: ../media/

[.lead]
You can configure the global health threshold values for all volumes to track any threshold breach. Appropriate events are generated for health threshold breaches, and you can take preventive measures based on these events. You can configure the global values based on the best practice settings for thresholds that apply to all monitored volumes.

== Before you begin

You must have the OnCommand Administrator or Storage Administrator role.

== About this task

Most of the threshold options have default values for better monitoring. However, you can change the values to suit the requirements of your environment.

Note that when Autogrow is enabled on a volume that capacity thresholds are considered breached based on the maximum volume size set by autogrow, not based on the original volume size.

== Steps

. In the left navigation pane, click *Configuration* > *Health Thresholds*.
. In the *Configuration/Health Thresholds* page, click *Volumes*.
. Configure the appropriate threshold values for capacity, Snapshot copies, qtree quotas, volume growth, and inodes.
. Click *Save*.
