---
permalink: online-help/task-restoring-database-backup-on-a-virtual-machine.html
sidebar: sidebar
keywords: 
summary: 'In case of data loss or data corruption, you can use the restore feature to restore Unified Manager to the previous stable state with minimal loss. You can restore the Unified Manager database on a virtual machine by using the Unified Manager maintenance console.'
---
= Restoring a database backup on a virtual machine
:icons: font
:imagesdir: ../media/

[.lead]
In case of data loss or data corruption, you can use the restore feature to restore Unified Manager to the previous stable state with minimal loss. You can restore the Unified Manager database on a virtual machine by using the Unified Manager maintenance console.

== Before you begin

* You must have the maintenance user credentials.
* The Unified Manager backup files must be on the local system.
* The backup files must be of `.7z` type.

== About this task

Backup compatibility is platform and version dependent. You can restore a backup from a virtual appliance to another virtual appliance, or from a virtual appliance to a Red Hat Enterprise Linux or CentOS system.

[NOTE]
====
When performing a restore operation on a different virtual appliance than the system from which the original backup file was created, the maintenance user name and password on the new vApp must be the same as the credentials from the original vApp.
====

== Steps

. In the vSphere client, locate the Unified Manager virtual machine, and then select the *Console* tab.
. Click in the console window, and then log in to the maintenance console using your user name and password.
. In the *Main Menu*, enter the number for the *System Configuration* option.
. In the *System Configuration Menu*, enter the number for the *Restore from an OCUM Backup* option.
. When prompted, enter the absolute path of the backup file.
+
----
Bundle to restore from: opt/netapp/data/ocum-backup/UM_9.4.N151112.0947_backup_unix_02-25-2018-11-41.7z
----
+
After the restore operation is complete, you can log in to Unified Manager.

== After you finish

After you restore the backup, if the OnCommand Workflow Automation server does not work, perform the following steps:

. On the Workflow Automation server, change the IP address of the Unified Manager server to point to the latest machine.
. On the Unified Manager server, reset the database password if the acquisition fails in step 1.
