---
permalink: online-help/task-rediscovering-clusters.html
sidebar: sidebar
keywords: 
summary: 'You can manually rediscover a cluster from the Configuration/Cluster Data Sources page page in order to obtain the latest information about the health, monitoring status, and performance status of the cluster.'
---
= Rediscovering clusters
:icons: font
:imagesdir: ../media/

[.lead]
You can manually rediscover a cluster from the Configuration/Cluster Data Sources page page in order to obtain the latest information about the health, monitoring status, and performance status of the cluster.

== About this task

You can manually rediscover a cluster when you want to update the cluster--such as by increasing the size of an aggregate when there is insufficient space--and you want Unified Manager to discover the changes that you make.

When Unified Manager is paired with OnCommand Workflow Automation (WFA), the pairing triggers the reacquisition of the data cached by WFA.

== Steps

. In the left navigation pane, click *Configuration* > *Cluster Data Sources*.
. On the *Configuration/Cluster Data Sources* page, click *Rediscover*.
+
Unified Manager rediscovers the selected cluster and displays the latest health and performance status.
+
[NOTE]
====
You can obtain the monitoring status of the cluster from the right pane of the Dashboards/Cluster View page.
====
