---
permalink: online-help/task_viewing_volume_protection_relationships.html
sidebar: sidebar
keywords: 
summary: 'From the Protection/Volume Relationships page, you can view the status of existing volume SnapMirror and SnapVault relationships. You can also examine details about protection relationships, including transfer and lag status, source and destination details, schedule and policy information, and so on.'
---
= Viewing volume protection relationships
:icons: font
:imagesdir: ../media/

[.lead]
From the Protection/Volume Relationships page, you can view the status of existing volume SnapMirror and SnapVault relationships. You can also examine details about protection relationships, including transfer and lag status, source and destination details, schedule and policy information, and so on.

== Before you begin

You must have the OnCommand Administrator or Storage Administrator role.

== About this task

You can also initiate relationship commands from this page.

== Steps

. In the left navigation pane, click *Protection* > *Volume Relationships*.
+
The Protection/Volume Relationships page is displayed.

. Choose one of the following ways to view the volume protection details:
 ** To view current information about all the volume relationships, remain on the default *All Volume Relationships* page.
 ** To view detailed information about the volume transfer trends over a period of time, in the View menu, select *Volume Transfer Status (Historical)*.
 ** To view detailed information about the volume transfer activity on a day to day basis, in the View menu, select *Volume Transfer Rate (Historical)*.

+
[NOTE]
====
The volume transfer views display information for volumes in asynchronous relationships only - volumes in synchronous relationships are not shown.
====

*Related information*

xref:task_exporting_storage_data_as_reports.adoc[Exporting data to CSV files for reporting]

xref:reference_relationship_all_relationships_view.adoc[Protection/Volume Relationships page]

xref:reference_relationship_last_1_month_transfer_status_view.adoc[Protection/Volume Transfer Status (Historical) page]

xref:reference_relationship_last_1_month_transfer_rate_view.adoc[Protection/Volume Transfer Rate (Historical) page]

xref:task_adding_users.adoc[Adding users]
