---
permalink: online-help/task-managing-report-schedules.html
sidebar: sidebar
keywords: 
summary: 'You can manage your report schedules from the Manage Report Schedules dialog box. You can add a new schedule and view, modify, or delete existing schedules.'
---
= Managing report schedules
:icons: font
:imagesdir: ../media/

[.lead]
You can manage your report schedules from the Manage Report Schedules dialog box. You can add a new schedule and view, modify, or delete existing schedules.

== Steps

. In the left navigation pane, click *Reports*, and then click *Manage Report Schedules*.
. In the *Manage Report Schedules* dialog box,
+
|===
| If you want to...| Then...
a|
View or modify an existing schedule
a|

 .. Select the schedule from the list displayed in the left pane.
+
The schedule details are displayed.

 .. Make the necessary changes.
 .. Click *Save* or *Save and Close*.

a|
Delete an existing schedule
a|

 .. Select the schedule from the list displayed in the left pane.
+
The schedule details are displayed.

 .. Click *Delete Schedule*.

a|
Add a new schedule
a|

 .. Click *Add Schedule*.
 .. A new schedule form appears in the right pane.
 .. Enter the schedule name, recipient email address, report format and frequency and select the reports you want to schedule.
 .. Click *Save*. The new schedule will be added in the Schedules list.

+
|===

*Related information*

xref:concept-what-report-scheduling-is.adoc[What report scheduling is]

xref:reference-manage-report-schedules-dialog-box-um-6-2.adoc[Manage Report Schedules dialog box]
