---
permalink: online-help/task-editing-the-infinite-volume-threshold-settings.html
sidebar: sidebar
keywords: 
summary: 'When you need to address any issues in your Infinite Volume’s storage space, you can edit the threshold settings of the Infinite Volume’s capacity based on your organization’s requirements. When a threshold is crossed, events are generated, and you receive notifications if you have configured alerts for such events.'
---
= Editing the Infinite Volume threshold settings
:icons: font
:imagesdir: ../media/

[.lead]
When you need to address any issues in your Infinite Volume's storage space, you can edit the threshold settings of the Infinite Volume's capacity based on your organization's requirements. When a threshold is crossed, events are generated, and you receive notifications if you have configured alerts for such events.

== Before you begin

You must have the OnCommand Administrator or Storage Administrator role.

== Steps

. In the left navigation pane, click *Health* > *SVMs*.
. In the *Health/Storage Virtual Machines* inventory page, select a SVM with Infinite Volume.
. In the *Health/Storage Virtual Machine* details page, click *Actions* > *Edit Thresholds*.
. In the *Edit SVM with Infinite Volume Thresholds* dialog box, modify the thresholds as required.
. Click *Save and Close*.

*Related information*

xref:task-adding-users.adoc[Adding users]
