---
permalink: online-help/task-viewing-the-volume-list-and-details.html
sidebar: sidebar
keywords: 
summary: 'From the Health/Volumes inventory page, you can monitor your inventory of volumes. The Health/Volumes Capacity and Utilization page enables you to view information about the capacity and utilization of volumes in a cluster.'
---
= Viewing the volume list and details
:icons: font
:imagesdir: ../media/

[.lead]
From the Health/Volumes inventory page, you can monitor your inventory of volumes. The Health/Volumes Capacity and Utilization page enables you to view information about the capacity and utilization of volumes in a cluster.

== Before you begin

You must have the Operator, OnCommand Administrator, or Storage Administrator role.

== About this task

You can also use the Health/Volume details page to view detailed information about volumes that are monitored, including the capacity, efficiency, configuration, and protection of the volumes. You can also view information about the related devices and related alerts for a specific volume.

== Steps

. In the left navigation pane, click *Health* > *Volumes*.
. Choose one of the following ways to view the volume details:
 ** To view detailed information about the capacity and utilization of volumes in a cluster, in the View menu, select *Volume Capacity and Utilization*.
 ** To view minimal details, position the cursor over the volume name.
 ** To view the complete details, click the volume name.
+
You can also view the complete details by clicking *View Details* in the minimal details dialog box.
. View the objects related to the volume by clicking *View Related* from the minimal details dialog box.

*Related information*

xref:reference-capacity-all-volumes-view.adoc[Health/Volumes Capacity and Utilization page]

xref:task-adding-users.adoc[Adding users]

xref:task-exporting-storage-data-as-reports.adoc[Exporting data to CSV files for reporting]

xref:task-adding-alerts.adoc[Adding alerts]

xref:reference-health-all-volumes-view.adoc[Health/Volumes inventory page]

xref:reference-health-volume-details-page.adoc[Health/Volume details page]

xref:task-editing-individual-volume-health-threshold-settings.adoc[Editing individual volume health threshold settings]
