---
permalink: online-help/task-viewing-the-list-of-snapshot-copies.html
sidebar: sidebar
keywords: 
summary: 'You can view the list of Snapshot copies for a selected volume. You can use the list of Snapshot copies to calculate the amount of disk space that can be reclaimed if one or more Snapshot copies are deleted, and you can delete the Snapshot copies if required.'
---
= Viewing the list of Snapshot copies
:icons: font
:imagesdir: ../media/

[.lead]
You can view the list of Snapshot copies for a selected volume. You can use the list of Snapshot copies to calculate the amount of disk space that can be reclaimed if one or more Snapshot copies are deleted, and you can delete the Snapshot copies if required.

== Before you begin

* You must have the Operator, OnCommand Administrator, or Storage Administrator role.
* The volume containing the Snapshot copies must be online.

== Steps

. In the left navigation pane, click *Health* > *Volumes*.
. In the *Health/Volumes* inventory page, select the volume that contains the Snapshot copies you want to view.
. In the *Health/Volume* details page, click the *Capacity* tab.
. In *Details* pane of the *Capacity* tab, in the Other Details section, click the link next to *Snapshot Copies*.
+
The number of Snapshot copies is a link that displays the list of Snapshot copies.

*Related information*

xref:reference-health-all-volumes-view.adoc[Health/Volumes inventory page]

xref:reference-health-volume-details-page.adoc[Health/Volume details page]
