---
permalink: online-help/task-restoring-data-using-the-health-volumes-page.html
sidebar: sidebar
keywords: 
summary: 'You can restore overwritten or deleted files, directories, or an entire volume from a Snapshot copy by using the restore feature on the Health/Volumes inventory page.'
---
= Restoring data using the Health/Volumes inventory page
:icons: font
:imagesdir: ../media/

[.lead]
You can restore overwritten or deleted files, directories, or an entire volume from a Snapshot copy by using the restore feature on the Health/Volumes inventory page.

== Before you begin

You must have the OnCommand Administrator or Storage Administrator role.

== About this task

You cannot restore NTFS file streams.

The restore option is not available when:

* The volume ID is unknown: for example, when you have a intercluster relationship and the destination cluster has not yet been discovered.
* The volume is a FlexGroup volume.
* The volume is configured for SnapMirror Synchronous replication.

== Steps

. In the *Health/Volumes* inventory page, select a volume from which you want to restore data.
. From the toolbar, click *Restore*.
+
The Restore dialog box is displayed.

. Select the volume and Snapshot copy from which you want to restore data, if different from the default.
. Select the items you want to restore.
+
You can restore the entire volume, or you can specify folders and files you want to restore.

. Select the location to which you want the selected items restored; either *Original Location* or *Alternate Location*.
. Click *Restore*.
+
The restore process begins.

*Related information*

xref:reference-restore-dialog-box.adoc[Restore dialog box]

xref:concept-executing-protection-workflows-using-wfa.adoc[Executing protection workflows using OnCommand Workflow Automation]
