---
permalink: online-help/task-configuring-event-retention-settings.html
sidebar: sidebar
keywords: 
summary: 'You can specify the number of days an event is retained in the Unified Manager server before it is automatically deleted. Only events that are resolved, obsolete, or of type Information are deleted. You can also specify the frequency with which these events are deleted or you can also manually delete the events.'
---
= Configuring event retention settings
:icons: font
:imagesdir: ../media/

[.lead]
You can specify the number of days an event is retained in the Unified Manager server before it is automatically deleted. Only events that are resolved, obsolete, or of type Information are deleted. You can also specify the frequency with which these events are deleted or you can also manually delete the events.

== Before you begin

You must have the OnCommand Administrator role to change the event settings.

== About this task

Retaining events for more than 180 days affects the server performance and is not recommended. The lower limit for the event retention period is 7 days; there is no upper limit.

== Steps

. In the left navigation pane, click *Configuration* > *Manage Events*.
. In the *Configuration/Manage Events* page, click the *Event Retention Settings* button.
. Configure the appropriate settings in the *Event Retention Settings* dialog box.
. Click *Save and Close*.
