---
permalink: online-help/task_identifying_the_best_node_for_a_busy_lif_using_the_cli.html
sidebar: sidebar
keywords: 
summary: 'You can display information about all the ports in a cluster. You can view information such as the network port role \(cluster, data, or node-management\), link status, maximum transmission unit \(MTU\), speed setting and operational status, and the port’s interface group, if applicable.'
---
= Identifying the best node for a busy LIF using the CLI
:icons: font
:imagesdir: ../media/

[.lead]
You can display information about all the ports in a cluster. You can view information such as the network port role (cluster, data, or node-management), link status, maximum transmission unit (MTU), speed setting and operational status, and the port's interface group, if applicable.

== Steps

. To display port information, enter the following command: `network port show`
+
The following example displays information about network ports that have a data role and are up in the cluster:
+
----
cluster1::> network port show  -role data -link up
                                   Auto-Negot Duplex      Speed (Mbps)
Node Port Role         Link  MTU   Admin/Oper Admin/Oper  Admin/Oper
---- ---- -----        ----  ----  ---------- ----------  ----------
node1
     e0M  data         up    1500  true/true  full/full   auto/100
     e0b  data         up    1500  true/true  full/full   auto/1000

node2
     e0b  data         up    1500  true/true  full/full   auto/1000
----

. Check for destination ports that are in the same network as the source home port and home node.
+
For example, the destination home port and home node should be on the same VLAN where applicable.

. To identify the least busy port, choose a data port that has the least number of connections.
