---
permalink: online-help/task-configuring-lag-threshold-settings-for-unmanaged-protection-relationships.html
sidebar: sidebar
keywords: 
summary: 'You can edit the global default lag warning and error health threshold settings for unmanaged protection relationships so that events are generated at intervals that are appropriate to your needs.'
---
= Editing lag health threshold settings for unmanaged protection relationships
:icons: font
:imagesdir: ../media/

[.lead]
You can edit the global default lag warning and error health threshold settings for unmanaged protection relationships so that events are generated at intervals that are appropriate to your needs.

== Before you begin

You must have the OnCommand Administrator or Storage Administrator role.

== About this task

The lag time must be no more than the defined transfer schedule interval. For example, if the transfer schedule is hourly, then the lag time must not be more than one hour. The lag threshold specifies a percentage that the lag time must not exceed. Using the example of one hour, if the lag threshold is defined as 150%, then you will receive an event when the lag time is more than 1.5 hours.

The settings described in this task are applied globally to all unmanaged protection relationships. The settings cannot be specified and applied exclusively to one unmanaged protection relationship.

== Steps

. In the left navigation pane, click *Configuration* > *Health Thresholds*.
. In the *Configuration/Health Thresholds* page, click *Relationships*.
. Increase or decrease the global default warning or error lag time percentage as required.
. Click *Save*.

*Related information*

xref:task-adding-users.adoc[Adding users]
