---
permalink: online-help/task_viewing_user_and_user_group_quotas.html
sidebar: sidebar
keywords: 
summary: 'The Health/Storage Virtual Machines inventory page displays information about the user and user group quotas that are configured on the SVM. You can view the name of the user or user group, limits set on the disks and files, used disk and file space, and email address for notification.'
---
= Viewing user and user group quotas
:icons: font
:imagesdir: ../media/

[.lead]
The Health/Storage Virtual Machines inventory page displays information about the user and user group quotas that are configured on the SVM. You can view the name of the user or user group, limits set on the disks and files, used disk and file space, and email address for notification.

== Before you begin

You must have one of the following roles to perform this task: Operator, OnCommand Administrator, or Storage Administrator.

== Steps

. In the left navigation pane, click *Health* > *SVMs*.
. In the *Health/Storage Virtual Machines* inventory page, select a SVM and then click the *User and Group Quotas* tab.

*Related information*

xref:task_adding_users.adoc[Adding users]

xref:concept_overview_of_the_quota_process_um_6_1.adoc[Overview of the quota process]
