---
permalink: online-help/task_sharing_reports.html
sidebar: sidebar
keywords: 
summary: 'You can email and share your reports with one or more users.'
---
= Sharing reports
:icons: font
:imagesdir: ../media/

[.lead]
You can email and share your reports with one or more users.

== Steps

. In the left navigation pane, click *Reports*, and then click *Run Report* for the report that you want.
+
The Report details page is displayed.

. Click *Actions* > *Share*.
. In the *Share Report* dialog box, specify the email address of the recipient with whom you want to share the report.
+
You can specify one or more email addresses, separated by commas.

. Specify the subject of the email.
+
By default, the name of the report appears as the subject of the email.

. Select the report format.
+
The _PDF_ option is selected as the default report format. If the XHTML format is selected, the recipient must open the report that is sent by email by using a supported web browser.

. Click *Share*.

*Related information*

xref:concept_what_report_sharing_is.adoc[What report sharing is]

xref:reference_share_report_dialog_box_um_6_2.adoc[Share Report dialog box]
