---
permalink: online-help/task_viewing_fabricpool_capacity_information.html
sidebar: sidebar
keywords: 
summary: 'You can view FabricPool capacity information for clusters, aggregates, and volumes on the Health inventory and details pages for these objects. You can also view FabricPool information in the Aggregate Capacity and Utilization report.'
---
= Viewing FabricPool capacity information
:icons: font
:imagesdir: ../media/

[.lead]
You can view FabricPool capacity information for clusters, aggregates, and volumes on the Health inventory and details pages for these objects. You can also view FabricPool information in the Aggregate Capacity and Utilization report.

== About this task

These pages display information such as the available capacity on the local performance tier and on the cloud tier, how much capacity is being used in both tiers, which aggregates are attached to a cloud tier, and which volumes are implementing the FabricPool features by moving certain information to the cloud tier.

== Steps

. Perform one of the following:
+
|===
| To view capacity information for...| Do this...
a|
Clusters
a|

 .. On the Health/Clusters inventory page, click a cluster.
 .. On the Health/Cluster details page, click the *Configuration* tab.
+
The display shows the names of any cloud tiers to which this cluster is connected.

a|
Aggregates
a|

 .. On the Health/Aggregates inventory page, click an aggregate where the Type field indicates "`SSD (FabricPool)`".
 .. On the Health/Aggregate details page, click the *Capacity* tab.
+
The display shows the total capacity, plus the used and free space in the cloud tier.

 .. Click the *Disk Information* tab.
+
The display shows the name of the cloud tier and the available space.

 .. Click the *Configuration* tab.
+
The display shows the name of the cloud tier and other detailed information about the object store.

a|
Volumes
a|

 .. On the Health/Volumes inventory page, click a volume where a policy name appears in the "`Tiering Policy`" field.
 .. On the Health/Volume details page, click the *Configuration* tab.
+
The display shows the name of the FabricPool tiering policy assigned to the volume.

+
|===

== After you finish

For more information on FabricPool aggregates, see the _ONTAP 9 Disks and Aggregates Power Guide_.

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html[ONTAP 9 Disks and Aggregates Power Guide]
