---
permalink: online-help/task_viewing_the_cluster_list_and_details.html
sidebar: sidebar
keywords: 
summary: 'You can use the Health/Clusters inventory page to view your inventory of clusters. The Health/Clusters Storage Summary page enables you to view summarized information about storage capacity and utilization in all clusters.'
---
= Viewing the cluster list and details
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Health/Clusters inventory page to view your inventory of clusters. The Health/Clusters Storage Summary page enables you to view summarized information about storage capacity and utilization in all clusters.

== Before you begin

You must have the Operator, OnCommand Administrator, or Storage Administrator role.

== About this task

You can also view details for individual clusters such as the cluster health, capacity, configuration, LIFs, nodes, and disks in that cluster by using the Health/Cluster details page.

The details in the Health/Clusters inventory page, Health/Clusters Storage Summary page, and the Health/Cluster details page help you plan your storage. For example, before provisioning a new aggregate, you can select a specific cluster from the Health/Clusters inventory page and obtain capacity details to determine if the cluster has the required space.

== Steps

. In the left navigation pane, click *Health* > *Clusters*.
. In the *View* menu, select *Storage Summary* to view details about storage capacity and utilization in all clusters
. View the complete details of the cluster in the *Health/Cluster* details page by clicking the cluster name.

*Related information*

xref:reference_capacity_all_clusters_view.adoc[Health/Clusters Storage Summary page]

xref:task_adding_users.adoc[Adding users]

xref:task_exporting_storage_data_as_reports.adoc[Exporting data to CSV files for reporting]

xref:task_adding_alerts.adoc[Adding alerts]

xref:task_editing_clusters.adoc[Editing clusters]

xref:reference_health_all_clusters_view.adoc[Health/Clusters inventory page]

xref:reference_health_cluster_details_page.adoc[Health/Cluster details page]
