---
permalink: online-help/task-editing-individual-qtree-health-threshold-settings.html
sidebar: sidebar
keywords: 
summary: 'You can edit the health threshold settings for qtree capacity for one or more qtrees. When a threshold is crossed, alerts are generated and you receive notifications. These notifications help you to take preventive measures based on the event generated.'
---
= Editing individual qtree health threshold settings
:icons: font
:imagesdir: ../media/

[.lead]
You can edit the health threshold settings for qtree capacity for one or more qtrees. When a threshold is crossed, alerts are generated and you receive notifications. These notifications help you to take preventive measures based on the event generated.

== Before you begin

You must have the OnCommand Administrator or Storage Administrator role.

== About this task

Based on changes to the threshold values, events are generated or obsoleted in the next monitoring cycle.

== Steps

. In the left navigation pane, click *Health* > *SVMs*.
. In the *Health/Storage Virtual Machines* inventory page, select the SVM on which the qtree resides.
. In the *Health/Storage Virtual Machine* details page, click the Qtrees tab.
. Select one or more qtrees and then click *Edit Thresholds*.
. In the *Edit Qtree Thresholds* dialog box, change the capacity thresholds for the selected qtree or qtrees and click *Save*.
