---
permalink: online-help/task-resuming-scheduled-transfers-on-a-quiesced-relationship-from-the-health-volume-details-page.html
sidebar: sidebar
keywords: 
summary: 'After you have quiesced a relationship to stop scheduled transfers from occurring, you can use Resume on the Health/Volume details page to reenable scheduled transfers so that data on the source or primary volume is protected. Transfers resume from a checkpoint, if one exists, at the next scheduled transfer interval.'
---
= Resuming scheduled transfers on a quiesced relationship from the Health/Volume details page
:icons: font
:imagesdir: ../media/

[.lead]
After you have quiesced a relationship to stop scheduled transfers from occurring, you can use *Resume* on the Health/Volume details page to reenable scheduled transfers so that data on the source or primary volume is protected. Transfers resume from a checkpoint, if one exists, at the next scheduled transfer interval.

== Before you begin

* You must have the OnCommand Administrator or Storage Administrator role.
* You must have set up Workflow Automation.

== Steps

. In the *Protection* tab of the *Health/Volume* details page, right-click in the topology view a quiesced relationship that you want to resume.
+
Alternatively, select *Resume* from the *Actions* > *Relationship* menu.

. In the *Resume* dialog box, click *Continue*.
+
You are returned to the Health/Volume details page.

. To view the related job tasks and to track their progress, click the job link that is displayed at the top of the *Health/Volume* details page.
. In the *Protection/Job* details page, click *Refresh* to update the tasks list and task details associated with the protection configuration job and to determine when the job is complete.
+
After the jobs are complete, data transfers are resumed at the next scheduled transfer interval.
