---
permalink: online-help/task-calculating-reclaimable-space-for-snapshot-copies.html
sidebar: sidebar
keywords: 
summary: 'You can calculate the amount of disk space that can be reclaimed if one or more Snapshot copies are deleted.'
---
= Calculating reclaimable space for Snapshot copies
:icons: font
:imagesdir: ../media/

[.lead]
You can calculate the amount of disk space that can be reclaimed if one or more Snapshot copies are deleted.

== Before you begin

You must have the Operator, OnCommand Administrator, or Storage Administrator role.

The volume must be online.

== Steps

. In the left navigation pane, click *Health* > *Volumes*.
. In the *Health/Volumes* inventory page, select the volume that contains the Snapshot copies you want to view.
+
The list of Snapshot copies is displayed.

. In the *Health/Volume* details page, click the *Capacity* tab.
. In *Details* pane of the *Capacity* tab, in the Other Details section, click the link next to *Snapshot Copies*.
+
The number of Snapshot copies is a link that displays the list of Snapshot copies.

. In the *Snapshot Copies* view, select the Snapshot copies for which you want to calculate the reclaimable space.
. Click *Calculate*.
+
The reclaimable space (in percentage, and KB, MB, GB, and so on) on the volume is displayed.

. To recalculate the reclaimable space, select the required Snapshot copies and click *Recalculate*.
