---
permalink: online-help/task-viewing-the-node-list-and-details.html
sidebar: sidebar
keywords: 
summary: 'You can use the Health/Nodes inventory page to view the list of nodes in your clusters. You can use the Health/Cluster details page to view detailed information about nodes that are part of the cluster that is monitored.'
---
= Viewing the node list and details
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Health/Nodes inventory page to view the list of nodes in your clusters. You can use the Health/Cluster details page to view detailed information about nodes that are part of the cluster that is monitored.

== Before you begin

You must have the Operator, OnCommand Administrator, or Storage Administrator role.

== About this task

You can view details such as the node state, cluster that contains the node, aggregate capacity details (used and total), and raw capacity details (usable, spare, and total). You can also obtain information about HA pairs, disks shelves, and ports.

== Steps

. In the left navigation pane, click *Health* > *Nodes*.
. On the *Health/Nodes* inventory page, click the node whose details you want to view.
+
The detailed information for the selected node is displayed in the Health/Cluster details page. The left pane displays the list of HA pairs. By default, the HA Details is open, which displays HA state details and events related to the selected HA pair.

. To view other details about the node, perform the appropriate action:
+
[options="header"]
|===
| To view...| Click...
a|
Details about the disk shelves
a|
*Disk Shelves*.
a|
Port-related information
a|
*Ports*.
|===
