---
permalink: online-help/task-creating-a-snapvault-protection-relationship-from-the-health-volumes-page.html
sidebar: sidebar
keywords: 
summary: 'You can use the Health/Volumes inventory page to create SnapVault relationships for one or more volumes on the same storage virtual machine \(SVM\) to enable data backups for protection purposes.'
---
= Creating a SnapVault protection relationship from the Health/Volumes inventory page
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Health/Volumes inventory page to create SnapVault relationships for one or more volumes on the same storage virtual machine (SVM) to enable data backups for protection purposes.

== Before you begin

You must have the OnCommand Administrator or Storage Administrator role.

== About this task

The *Protect* menu does not display in the following instances:

* If RBAC settings do not allow this action: for example, if you have only operator privileges
* When the volume ID is unknown: for example, when you have a intercluster relationship and the destination cluster has not yet been discovered

== Steps

. In the left navigation pane, click *Health* > *Volumes*.
. In the *Health/Volumes* inventory page, right-click a volume you want to protect and select *Protect*.
+
Alternatively, to create multiple protection relationships on the same storage virtual machine (SVM), select one or more volumes in the Health/Volumes inventory page, and click *Protect* on the toolbar.

. Select *SnapVault* from the menu.
+
The Configure Protection dialog box is launched.

. Click *SnapVault* to view the *SnapVault* tab and to configure the secondary volume information.
. Click *Advanced* to set deduplication, compression, autogrow, and space guarantee as needed, and then click *Apply*.
. Complete the *Destination Information* area and the *Relationship Settings* area in the *SnapVault* tab.
. Click *Apply*.
+
You are returned to the Health/Volumes inventory page.

. Click the protection configuration job link at the top of the *Health/Volumes* inventory page.
+
If you are creating only one protection relationship, the Protection/Job details page is displayed; however, if you are creating more than one protection relationship, a filtered list of all the jobs associated with the protection operation is displayed.

. Do one of the following:
 ** If you have only one job, click *Refresh* to update the tasks list and task details associated with the protection configuration job and to determine when the job is complete.
 ** If you have more than one job:
  ... Click a job in the jobs list.
  ... Click *Refresh* to update the tasks list and task details associated with the protection configuration job and to determine when the job is complete.
  ... Use the *Back* button to return to the filtered list and view another job.
