---
permalink: online-help/task-deleting-svm-associations.html
sidebar: sidebar
keywords: 
summary: 'You can delete SVM associations for partner applications to remove the secondary provisioning relationship between source and destination SVMs; for example, you might do this when the destination SVM is full and you want to create a new SVM protection association.'
---
= Deleting SVM associations
:icons: font
:imagesdir: ../media/

[.lead]
You can delete SVM associations for partner applications to remove the secondary provisioning relationship between source and destination SVMs; for example, you might do this when the destination SVM is full and you want to create a new SVM protection association.

== Before you begin

You must have the OnCommand Administrator or Storage Administrator role.

== About this task

The *Delete* button is disabled until at least one SVM association is selected. Changing associations using the delete and create functions affects only future provisioning operations; it does not move existing destination volumes.

== Steps

. In the left navigation pane, click *Protection* > *SVM Associations*.
. Select at least one SVM association.
+
The *Delete* button is enabled.

. Click *Delete.*
+
A warning dialog box is displayed.

. Click *Yes* to continue.
+
The selected SVM association is removed from the list.
