---
settings:
  name: OnCommand Unified Manager 9.5
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
  versions:
    - name: Unified Manager
      url: /oncommand-unified-manager-95
      version-number: "9.5"
    - name: Unified Manager
      url: /active-iq-unified-manager-99
      version-number: "9.9"
    - name: Unified Manager
      url: /active-iq-unified-manager-98
      version-number: "9.8"
    - name: Unified Manager
      url: /active-iq-unified-manager-97
      version-number: "9.7"
sidebar:
  entries:
    - title: OnCommand Unified Manager 9.5 docs
      url: "/index.html"
    - title: Release notes
      url: "/release-notes.html"
    - title: Get started
      entries:
      - title: Quick start install for VMware vSphere
        url: "/qsg-vapp.html"
      - title: Quick start install for Linux
        url: "/qsg-linux.html"
      - title: Quick start install for Windows
        url: "/qsg-windows.html"
    - section: install
    - section: config
    - section: online-help
    - section: performance-checker
    - section: health-checker
    - title: Legal notices
      url: "/legal-notices.html"
homepage:
  tiles:
    - title: Get started
      links:
        - title: Release notes
          url: /release-notes.html
        - title: Quick start install for VMware vSphere
          url: qsg-vapp.html
        - title: Quick start install for Linux
          url: qsg-linux.html
        - title: Quick start install for Windows
          url: qsg-windows.html 
    - title: Install & configure Unified Manager
      links:
        - title: Install & upgrade on VMware vSphere systems
          url: install/concept-installing-upgrading-and-removing-unified-manager-software-on-vmware-vsphere.html
        - title: Install & upgrade on Linux systems
          url: install/concept-install-upgrade-and-remove-unified-manager-software.html
        - title: Install & upgrade on Windows systems
          url: install/concept-installing-upgrading-and-removing-unified-manager-software.html
        - title: Configure Unified Manager
          url: config/concept-configuring-unified-manager.html
    - title: Performance monitoring
      links:
        - title: Performance thresholds
          url: performance-checker/concept-managing-performance-thresholds.html
        - title: Cluster performance
          url: performance-checker/concept-monitoring-cluster-performance-from-the-dashboard.html
    - title: More resources
      links:
        - title: Unified Manager videos
          url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
        - title: Unified Manager blogs 
          url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish-date-mktg%20descending&layout=card&f:@facet-language-mktg=[English] 
        - title: Documentation for the latest version of Active IQ Unified Manager
          url: https://docs.netapp.com/us-en/active-iq-unified-manager/index.html
