---
settings:
  name: Catalyst migration
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
  versions:
    - name: OnCommand Unified Manager
      url: /oncommand-unified-manager-95
      version-number: "9.5"
    - name: Active IQ Unified Manager
      url: /active-iq-unified-manager-99
      version-number: "9.9"
    - name: Active IQ Unified Manager
      url: /active-iq-unified-manager-98
      version-number: "9.8"
    - name: Active IQ Unified Manager
      url: /active-iq-unified-manager-97
      version-number: "9.7"
sidebar:
  entries:
    - title: Home
      url: "/index.html"
    - section: install
    - section: config
    - section: online-help
    - section: performance-checker
    - section: health-checker
    - title: Legal
      url: "/legal-notices.html"
homepage:
  tiles:
    - title: Get started
      links:
        - title: Perform configuration and administrative tasks
          url: config/index.html
    - title: More resources
      links:
        - title: Documentation for the latest version of Active IQ Unified Manager
          url: https://docs.netapp.com/us-en/active-iq-unified-manager/
