---
settings:
  name: Catalyst migration
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
  versions:
    - name: Unified Manager
      url: /oncommand-unified-manager-95
      version-number: "9.5"
    - name: Unified Manager
      url: /active-iq-unified-manager-99
      version-number: "9.9"
    - name: Unified Manager
      url: /active-iq-unified-manager-98
      version-number: "9.8"
    - name: Unified Manager
      url: /active-iq-unified-manager-97
      version-number: "9.7"
sidebar:
  entries:
    - title: Home
      url: "/index.html"
    - title: Release notes
      url: "/release-notes.html"
    - title: Quick start install for VMware vSphere
      url: "/qsg-vapp.html"
    - title: Quick start install for Linux
      url: "/qsg-linux.html"
    - title: Quick start install for Windows
      url: "/qsg-windows.html"
    - section: install
    - section: config
    - section: online-help
    - section: performance-checker
    - section: health-checker
    - title: Legal
      url: "/legal-notices.html"
homepage:
  tiles:
    - title: Get started
      links:
        - title: Release notes
          url: /release-notes.html
        - title: Quick start install for VMware vSphere
          url: qsg-vapp.html
        - title: Quick start install for Linux
          url: qsg-linux.html
        - title: Quick start install for Windows
          url: qsg-windows.html 
    - title: Install & configure Unified Manager
      links:
        - title: Install & upgrade on VMware vSphere systems
          url: install-vapp/concept-requirements-for-installing-unified-manager.html
        - title: Install & upgrade on Linux systems
          url: install-linux/concept-requirements-for-installing-unified-manager.html
        - title: Install & upgrade on Windows systems
          url: install-windows/concept-requirements-for-installing-unified-manager.html
        - title: Configure Unified Manager
          url: config/concept-configuring-unified-manager.html
    - title: Performance monitoring
      links:
        - title: Performance thresholds
          url: performance-checker/concept-managing-performance-thresholds.html
        - title: Cluster performance
          url: performance-checker/concept-monitoring-cluster-performance-from-the-dashboard.html
        - title: QoS policy group
          url: performance-checker/concept-managing-performance-using-qos-policy-group-information.html  
    - title: Data protection monitoring
      links:
        - title: Set up protection relationship
          url: /data-protection/task-setting-up-protection-relationships-in-unified-manager.html
        - title: Perform failover and failback
          url: /data-protection/task-performing-protection-relationship-failover-and-failback.html
        - title: Manage protection relationship
          url: /data-protection/concept-managing-and-monitoring-protection-relationships.html
        - title: Generate reports
          url: /reporting/concept-unified-manager-reporting.html
    - title: Use REST APIs
      links:
        - title: Get started
          url: /api-automation/concept-api-url-and-categories.html
        - title: Access Unified Manager APIs
          url: /api-automation/concept-rest-api-accessing-and-authentication-in-um-apis.html
        - title: Access ONTAP APIs
          url: /api-automation/concept-gateway-apis.html             
    - title: More resources
      links:
        - title: Unified Manager videos
          url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
        - title: Unified Manager blogs 
          url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish-date-mktg%20descending&layout=card&f:@facet-language-mktg=[English] 
        - title: Documentation for the latest version of Active IQ Unified Manager
          url: https://docs.netapp.com/us-en/active-iq-unified-manager/index.html
