---
settings:
  name: Catalyst migration
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
sidebar:
  entries:
    - title: Home
      url: "/index.html"
    - section: install
    - section: config
    - section: online-help
    - section: performance-checker
    - section: health-checker
    - title: Legal
      url: "/legal-notices.html"
homepage:
  tiles:
    - title: Get started
      links:
        - title: Perform configuration and administrative tasks
          summary: This is the description of the link target
          url: config/index.html
