---
permalink: qsg-windows.html
sidebar: sidebar
keywords: quick start guide, getting started, QSG, Windows QSG, quick installation, Windows installer
summary: "Quick start guide for Unified Manager on Linux platform."
---
= Quick start instructions for Windows installations

== System requirements

* Operating Systems: Microsoft Windows Server 2012, 2012 R2, and 2016 64-bit Standard and Datacenter Editions
*	RAM: 12 GB
*	CPU: 9572 MHz total
*	Free disk space: 100 GB of disk space for the installation directory, 50 GB of disk space for the MySQL data directory

For detailed system requirements, see link:install/reference-windows-software-and-installation-requirements.html[Windows software and installation requirements] and link:http://mysupport.netapp.com/matrix[Interoperability Matrix].

== Installing OnCommand Unified Manager

=== Download the installer
.	Download the `OnCommandUnifiedManager-9.5RC1.exes` installation package.
.	Copy the installation file to a directory on the target system.

=== Install Unified Manager
Microsoft .NET 4.5.2, or greater, must be installed. Unified Manager installs other required third-party packages as part of the installation. If you need more information on the dependent software packages, see link:install/concept-installing-upgrading-and-removing-unified-manager-software.html[Installing, upgrading, and removing Unified Manager software on Windows].

.	Log in to Windows using the default local administrator account.
.	In the directory where you downloaded the installation file, right-click and run the Unified Manager executable (.exe) file as an administrator.
.	When prompted, enter the user name and password to create the Unified Manager maintenance user.
.	In the Database Connection wizard, enter the MySQL root password.
.	Follow the remaining prompts to complete the installation.
.	Click *Finish* at the end of the installation and the Unified Manager web UI is displayed.