---
permalink: performance-checker/concept-collecting-data-and-monitoring-workload-performance.html
sidebar: sidebar
keywords: 
summary: 'Unified Manager collects and analyzes workload activity every 5 minutes to identify performance events, and it detects configuration changes every 15 minutes. It retains a maximum of 30 days of 5-minute historical performance and event data, and it uses this data to forecast the expected range for all monitored workloads.'
---
= Collecting data and monitoring workload performance
:icons: font
:imagesdir: ../media/

[.lead]
Unified Manager collects and analyzes workload activity every 5 minutes to identify performance events, and it detects configuration changes every 15 minutes. It retains a maximum of 30 days of 5-minute historical performance and event data, and it uses this data to forecast the expected range for all monitored workloads.

[NOTE]
====
This chapter describes how dynamic thresholds work and how they are used to help monitor workload performance. This chapter is not applicable for statistics or events caused by user-defined or system-defined performance threshold breaches.
====

Unified Manager must collect a minimum of 3 days of workload activity before it can begin its analysis and before the expected range for I/O response time and operations can be displayed on the Performance/Volume Details page and in the Event details page. While this activity is being collected, the expected range does not display all changes occurring from workload activity. After collecting 3 days of activity, Unified Manager adjusts the expected range, every 24 hours at 12:00 a.m., to reflect workload activity changes and establish a more accurate performance threshold.

During the first 4 days that Unified Manager is monitoring a volume, if more than 24 hours have passed since the last data collection, the charts on the Performance/Volume Details page will not display the expected range for that volume. Events detected prior to the last collection are still available.

[NOTE]
====
Daylight savings time (DST) changes the system time, which alters the expected range of performance statistics for monitored workloads. Unified Manager immediately begins to correct the expected range, which takes approximately 15 days to complete. During this time you can continue to use Unified Manager, but, since Unified Manager uses the expected range to detect events, some events might not be accurate. Events detected prior to the time change are not affected. Manually changing the time on a cluster, or on a Unified Manager server, to an earlier time will also affect the event analysis results.
====

*Related information*

xref:concept-what-the-expected-range-of-performance-is.adoc[What the expected range of performance is]

xref:reference-workload-performance-measurement-values.adoc[Workload performance measurement values]
