---
permalink: performance-checker/task-investigating-perceived-slow-response-time-for-a-workload.html
sidebar: sidebar
keywords: 
summary: 'You can use Unified Manager to determine whether operations on the cluster might have contributed to the slow response time \(latency\) for a volume workload.'
---
= Investigating a perceived slow response time for a workload
:icons: font
:imagesdir: ../media/

[.lead]
You can use Unified Manager to determine whether operations on the cluster might have contributed to the slow response time (latency) for a volume workload.

== Before you begin

* You must have the Operator, OnCommand Administrator, or Storage Administrator role.
* You must have identified the name of the volume, or associated LUN, you want to analyze.
* Unified Manager must have collected and analyzed a minimum of five days of performance statistics from the cluster.

== About this task

If you are viewing the Event details page, you can click the name for a volume to go directly to the Performance/Volume Details page.

== Steps

. In the *Search* bar, type the name of the volume.
+
The name of the volume is displayed in the search results.

. Click the name of the volume.
+
The volume is displayed on the Performance/Volume Details page.

. On the Historic data chart, click *5d* to display the last five days of historical data.
. Review the *IOPS* chart to answer the following questions:
 ** Are there dramatic spikes in the activity?
 ** Are there dramatic drops in the activity?
 ** Are there abnormal changes in the operations pattern?
If the operations do not display dramatic spikes or drops in activity, and there were no changes to the cluster configuration during this time, the storage administrator can confirm that other workloads have not impacted volume performance.
. On the *Break down data by* menu, under *IOPS*, select ***Reads/writes/other***.
. Click *Submit*.
+
The Reads/writes/other chart is displayed below the IOPS chart.

. Review the *Reads/writes/other* chart to identify dramatic spikes or drops in the amount of reads or writes for the volume.
+
If there are no dramatic spikes or drops in reads or writes, the storage administrator can confirm that I/O on the cluster is operating normally. Any performance issues might be on the network or the connected clients.

*Related information*

xref:task-determining-whether-a-workload-has-a-performance-issue.adoc[Determining whether a workload has a performance issue]

xref:concept-types-of-workloads-monitored-by-unified-manager.adoc[Types of workloads monitored by Unified Manager]

xref:concept-how-unified-manager-uses-workload-response-time-to-identify-performance-issues.adoc[How Unified Manager uses workload latency to identify performance issues]

xref:concept-how-graphs-of-performance-data-work.adoc[How graphs of performance data work]
