---
permalink: health-checker/reference_what_the_suggested_actions_section_displays.html
sidebar: sidebar
keywords: 
summary: 'The Suggested Actions section of the Event details page provides possible reasons for the event and suggests a few actions so that you can try to resolve the event on your own. The suggested actions are customized based on the type of event or type of threshold that has been breached.'
---
= What the Suggested Actions section displays
:icons: font
:imagesdir: ../media/

[.lead]
The Suggested Actions section of the Event details page provides possible reasons for the event and suggests a few actions so that you can try to resolve the event on your own. The suggested actions are customized based on the type of event or type of threshold that has been breached.

This area is displayed only for some types of events.

In some cases there are *Help* links provided on the page that reference additional information for many suggested actions, including instructions for performing a specific action. Some of the actions may involve using Unified Manager, OnCommand System Manager, OnCommand Workflow Automation, ONTAP CLI commands, or a combination of these tools.

There are also some links provided in this help topic.

You should consider the actions suggested here as only a guidance in resolving this event. The action you take to resolve this event should be based on the context of your environment.
