---
permalink: health-checker/reference-description-of-event-impact-levels.html
sidebar: sidebar
keywords: 
summary: 'Each event is associated with an impact level \(Incident, Risk, or Event\) to help you prioritize the events that require immediate corrective action.'
---
= Description of event impact levels
:icons: font
:imagesdir: ../media/

[.lead]
Each event is associated with an impact level (Incident, Risk, or Event) to help you prioritize the events that require immediate corrective action.

* *Incident*
+
An incident is a set of events that can cause a cluster to stop serving data to the client and run out of space for storing data. Events with an impact level of Incident are the most severe. Immediate corrective action should be taken to avoid service disruption.

* *Risk*
+
A risk is a set of events that can potentially cause a cluster to stop serving data to the client and run out of space for storing data. Events with an impact level of Risk can cause service disruption. Corrective action might be required.

* *Event*
+
An event is a state or status change of storage objects and their attributes. Events with an impact level of Event are informational and do not require corrective action.
