---
permalink: health-checker/task-editing-individual-volume-health-threshold-settings.html
sidebar: sidebar
keywords: 
summary: 'You can edit the health threshold settings for volume capacity, growth, quota, and space reserve of one or more volumes. When a threshold is crossed, alerts are generated and you receive notifications. These notifications help you to take preventive measures based on the event generated.'
---
= Editing individual volume health threshold settings
:icons: font
:imagesdir: ../media/

[.lead]
You can edit the health threshold settings for volume capacity, growth, quota, and space reserve of one or more volumes. When a threshold is crossed, alerts are generated and you receive notifications. These notifications help you to take preventive measures based on the event generated.

== Before you begin

You must have the OnCommand Administrator or Storage Administrator role.

== About this task

Based on changes to the threshold values, events are generated or obsoleted in the next monitoring cycle.

Note that when Autogrow is enabled on a volume that capacity thresholds are considered breached based on the maximum volume size set by autogrow, not based on the original volume size.

== Steps

. In the left navigation pane, click *Health* > *Volumes*.
. In the *Health/Volumes* inventory page, select one or more volumes and then click *Edit Thresholds*.
. In the *Edit Volume Thresholds* dialog box, edit the threshold settings of one of the following: capacity, Snapshot copies, qtree quota, growth, or inodes by selecting the appropriate check box and then modifying the settings.
. Click *Save*.
