---
permalink: health-checker/task_removing_a_protection_relationship_from_the_health_volume_details_page.html
sidebar: sidebar
keywords: 
summary: 'You can remove a protection relationship to permanently delete an existing relationship between the selected source and destination: for example, when you want to create a relationship using a different destination. This operation removes all metadata and cannot be undone.'
---
= Removing a protection relationship from the Health/Volume details page
:icons: font
:imagesdir: ../media/

[.lead]
You can remove a protection relationship to permanently delete an existing relationship between the selected source and destination: for example, when you want to create a relationship using a different destination. This operation removes all metadata and cannot be undone.

== Before you begin

* You must have the OnCommand Administrator or Storage Administrator role.
* You must have set up Workflow Automation.

== Steps

. In the *Protection* tab of the *Health/Volume* details page, select from the topology the SnapMirror relationship you want to remove.
. Right-click the name of the destination and select *Remove* from the menu.
+
The Remove Relationship dialog box is displayed.

. Click *Continue* to remove the relationship.
+
The relationship is removed from the Health/Volume details page.
