---
permalink: health-checker/task-editing-storage-class-threshold-settings.html
sidebar: sidebar
keywords: 
summary: 'When you need to address any issues related to storage space in your storage classes, you can edit the threshold settings of the storage class capacity based on your organization’s requirements. When the threshold is crossed, events are generated, and you receive notifications if you have configured alerts for such events.'
---
= Editing the threshold settings of storage classes
:icons: font
:imagesdir: ../media/

[.lead]
When you need to address any issues related to storage space in your storage classes, you can edit the threshold settings of the storage class capacity based on your organization's requirements. When the threshold is crossed, events are generated, and you receive notifications if you have configured alerts for such events.

== Before you begin

You must have the OnCommand Administrator or Storage Administrator role.

== Steps

. In the left navigation pane, click *Health* > *SVMs*.
. In the *Health/Storage Virtual Machines* inventory page, select an SVM with Infinite Volume.
. In the *Health/Storage Virtual Machine* details page, click *Actions* > *Edit Thresholds*.
. In the *Edit Storage Class Thresholds* dialog box, modify the thresholds as required.
. Click *Save and Close*.
