---
permalink: health-checker/task-changing-the-umadmin-password-on-rhel.html
sidebar: sidebar
keywords: 
summary: 'For security reasons, you must change the default password for the Unified Manager umadmin user immediately after completing the installation process. If necessary, you can change the password again anytime later.'
---
= Changing the umadmin password on Linux systems
:icons: font
:imagesdir: ../media/

[.lead]
For security reasons, you must change the default password for the Unified Manager umadmin user immediately after completing the installation process. If necessary, you can change the password again anytime later.

== Before you begin

* Unified Manager must be installed on a Red Hat Enterprise Linux or CentOS Linux system.
* You must have the root user credentials for the Linux system on which Unified Manager is installed.

== Steps

. Log in as the root user to the Linux system on which Unified Manager is running.
. Change the umadmin password: `passwd umadmin`
+
The system prompts you to enter a new password for the umadmin user.

== After you finish

If Unified Manager is installed in a Veritas Cluster Server (VCS) environment, you must change the umadmin password on the second node of the VCS setup. The umadmin password for both nodes must be the same.
