---
permalink: health-checker/task-breaking-a-snapmirror-relationship-from-the-health-volume-details-page.html
sidebar: sidebar
keywords: 
summary: 'You can break a protection relationship from the Health/Volume details page and stop data transfers between a source and destination volume in a SnapMirror relationship. You might break a relationship when you want to migrate data, for disaster recovery, or for application testing. The destination volume is changed to a read-write volume. You cannot break a SnapVault relationship.'
---
= Breaking a SnapMirror relationship from the Health/Volume details page
:icons: font
:imagesdir: ../media/

[.lead]
You can break a protection relationship from the Health/Volume details page and stop data transfers between a source and destination volume in a SnapMirror relationship. You might break a relationship when you want to migrate data, for disaster recovery, or for application testing. The destination volume is changed to a read-write volume. You cannot break a SnapVault relationship.

== Before you begin

* You must have the OnCommand Administrator or Storage Administrator role.
* You must have set up Workflow Automation.

== Steps

. In the *Protection* tab of the *Health/Volume* details page, select from the topology the SnapMirror relationship you want to break.
. Right-click the destination and select *Break* from the menu.
+
The Break Relationship dialog box is displayed.

. Click *Continue* to break the relationship.
. In the topology, verify that the relationship is broken.

*Related information*

xref:task-performing-a-protection-relationship-failover-and-failback.adoc[Performing a protection relationship failover and failback]

xref:task-configuring-a-connection-between-workflow-automation-and-unified-manager.adoc[Configuring a connection between Workflow Automation and Unified Manager]
