---
permalink: health-checker/task_restoring_a_mysql_database_backup_on_windows.html
sidebar: sidebar
keywords: 
summary: 'In case of data loss or data corruption, you can use the restore feature to restore Unified Manager to the previous stable state with minimal loss. You can restore the Unified Manager database to a local Windows system or a remote Windows system by using the restore command.'
---
= Restoring a database backup on Windows
:icons: font
:imagesdir: ../media/

[.lead]
In case of data loss or data corruption, you can use the restore feature to restore Unified Manager to the previous stable state with minimal loss. You can restore the Unified Manager database to a local Windows system or a remote Windows system by using the restore command.

== Before you begin

* You must have Unified Manager installed on a server.
* You must have Windows administrator privileges.
* You must have copied the Unified Manager backup file and the contents of the database repository directory to the system on which you will perform the restore operation.
+
It is recommended that you copy the backup file to the default directory `\ProgramData\NetApp\OnCommandAppData\ocum\backup`. The database repository files must be copied to the `\database_dumps_repo` subdirectory under the `\backup` directory.

* The backup files must be of `.7z` type.

== About this task

The restore feature is platform-specific and version-specific. You can restore a Unified Manager backup only on the same version of Unified Manager, and a Windows backup can be restored only on a Windows platform.

[TIP]
====
If the folder names contain a space, you must include the absolute path or relative path of the backup file in double quotation marks.
====

== Steps

. If you are performing a restore onto a new server, after installing Unified Manager do not launch the UI or configure any clusters, users, or authentication settings when the installation is complete. The backup file populates this information during the restore process.
. Log in to the Unified Manager console as an administrator: `um cli login -u maint_username`
. At the command prompt, restore the backup: `um backup restore -f <backup_file_path>/<backup_file_name>`
+
`um backup restore -f \ProgramData\NetApp\OnCommandAppData\ocum\backup\UM_9.4.N151118.2300_backup_windows_02-20-2018-02-51.7z`

== After you finish

After the restore operation is complete, you can log in to Unified Manager.
