---
permalink: config/task-adding-clusters.html
sidebar: sidebar
keywords: 
summary: 'You can add a cluster to OnCommand Unified Manager so that you can monitor the cluster. This includes the ability to obtain cluster information such as the health, capacity, performance, and configuration of the cluster so that you can find and resolve any issues that might occur.'
---
= Adding clusters
:icons: font
:imagesdir: ../media/

[.lead]
You can add a cluster to OnCommand Unified Manager so that you can monitor the cluster. This includes the ability to obtain cluster information such as the health, capacity, performance, and configuration of the cluster so that you can find and resolve any issues that might occur.

== Before you begin

* You must have the OnCommand Administrator or Storage Administrator role.
* You must have the following information:
 ** Host name or cluster-management IP address
+
The host name is the FQDN or short name that Unified Manager uses to connect to the cluster. The host name must resolve to the cluster-management IP address.
+
The cluster-management IP address must be the cluster-management LIF of the administrative storage virtual machine (SVM). If you use a node-management LIF, the operation fails.

 ** Data ONTAP administrator user name and password
+
This account must have the _admin_ role with Application access set to _ontapi_, _ssh_, and _http_.

 ** Type of protocol (HTTP or HTTPS) that can be configured on the cluster and the port number used to connect to the cluster

+
[NOTE]
====
You can add clusters which are behind a NAT/firewall by using the Unified Manager NAT IP address. Any connected Workflow Automation or SnapProtect systems must also be behind the NAT/firewall, and SnapProtect API calls must use the NAT IP address to identify the cluster.
====
* The Unified Manager FQDN must be able to ping the ONTAP system.
+
You can verify this by using the following ONTAP command: `ping -node node_name -destination Unified_Manager_FQDN`.

* You must have adequate space on the Unified Manager server. You are prevented from adding a cluster to the server when greater than 90% of space in the database directory is already consumed.

== About this task

For a MetroCluster configuration, you must add both the local and remote clusters, and the clusters must be configured correctly.

You can monitor a single cluster by two instances of Unified Manager provided that you have configured a second cluster-management LIF on the cluster so that each instance of Unified Manager connects through a different LIF.

== Steps

. In the left navigation pane, click *Configuration* > *Cluster Data Sources*.
. On the *Configuration/Cluster Data Sources* page, click *Add*.
. In the *Add Cluster* dialog box, specify the required values, such as the host name or IP address of the cluster, user name, password, protocol for communication, and port number.
+
By default, the HTTPS protocol and port 443 are selected.
+
You can change the cluster-management IP address from IPv6 to IPv4 or from IPv4 to IPv6. The new IP address is reflected in the cluster grid and the cluster configuration page after the next monitoring cycle is complete.

. Click *Submit*.
. If HTTPS is selected, perform the following steps:
 .. In the *Authorize Host* dialog box, click *View Certificate* to view the certificate information about the cluster.
 .. Click *Yes*.
+
Unified Manager checks the certificate only when the cluster is added initially. Unified Manager does not check the certificate for each API call to ONTAP.
+
If the certificate has expired, you cannot add a new cluster. You must first renew the SSL certificate and then add the cluster.

== Results

After all the objects for a new cluster are discovered (about 15 minutes), Unified Manager starts to gather historical performance data for the previous 15 days. These statistics are collected using the data continuity collection functionality. This feature provides you with over two weeks of performance information for a cluster immediately after it is added. After the data continuity collection cycle is completed, real-time cluster performance data is collected, by default, every five minutes.

[NOTE]
====
Because the collection of 15 days of performance data is CPU intensive, it is suggested that you stagger the addition of new clusters so that data continuity collection polls are not running on too many clusters at the same time. Additionally, if you restart Unified Manager during the data continuity collection period, the collection will be halted and you will see gaps in the performance charts for the missing timeframe.
====

[TIP]
====
If you receive an error message that you cannot add the cluster, check to see if the following issues exist:

* If the clocks on the two systems are not synchronized and the Unified Manager HTTPS certificate start date is later than the date on the cluster. You must ensure that the clocks are synchronized using NTP or a similar service.
* If the cluster has reached the maximum number of EMS notification destinations the Unified Manager address cannot be added. By default only 20 EMS notification destinations can be defined on the cluster.

====
