---
permalink: config/task-restarting-the-unified-manager-virtual-machine.html
sidebar: sidebar
keywords: 
summary: 'You can restart the virtual machine from the maintenance console of Unified Manager. You must restart after generating a new security certificate or if there is a problem with the virtual machine.'
---
= Restarting the Unified Manager virtual machine
:icons: font
:imagesdir: ../media/

[.lead]
You can restart the virtual machine from the maintenance console of Unified Manager. You must restart after generating a new security certificate or if there is a problem with the virtual machine.

== Before you begin

The virtual appliance is powered on.

You are logged in to the maintenance console as the maintenance user.

== About this task

You can also restart the virtual machine from vSphere by using the **Restart Guest** option. See the VMware documentation for more information.

== Steps

. Access the maintenance console.
. Select *System Configuration* > *Reboot Virtual Machine*.

*Related information*

xref:task-changing-the-unified-manager-host-name-on-vmware.adoc[Changing the Unified Manager virtual appliance host name]
