---
permalink: install/concept-requirements-for-unified-manager-in-vcs.html
sidebar: sidebar
keywords: 
summary: 'Before installing Unified Manager in a Veritas Cluster Server \(VCS\) environment, you must ensure that the cluster nodes are properly configured to support Unified Manager.'
---
= Requirements for Unified Manager in VCS
:icons: font
:imagesdir: ../media/

[.lead]
Before installing Unified Manager in a Veritas Cluster Server (VCS) environment, you must ensure that the cluster nodes are properly configured to support Unified Manager.

You must ensure that the VCS configuration meets the following requirements:

* Both the cluster nodes must be running a supported operating system version.
* The same version of Unified Manager must be installed using the same path on both the cluster nodes.
* The MySQL user on both the nodes must have the same user ID and group ID.
* Native ext3, ext4 file systems, and Logical Volume Manager (LVM) must be used.
* Unified Manager must be connected to the storage system through Fibre Channel (FC) or iSCSI.
+
You must also ensure that the FC link is active and that the LUNs created on the storage systems are accessible to both the cluster nodes.

* The shared data disk must have enough space (minimum 80 GB) for the Unified Manager database, reports, certificates, and script plug-in folders.
* A minimum of two network interfaces must be set up on each system: one for node-to-node communication and the other for node-to-client communication.
+
The name of the network interface used for node-to-client communication must be the same on both the systems.

* A separate heartbeat link must be established between the cluster nodes; otherwise, the network interface is used to communicate between the cluster nodes.
* Optional: SnapDrive for UNIX should be used to create a shared location that is accessible to both the nodes in a high availability setup.
+
See the _SnapDrive for UNIX Installation and Administration Guide_ for information about installing and creating a shared location. You can also manage LUNs using SnapDrive or the storage system command-line interface. See the SnapDrive for UNIX compatibility matrix for more information.

* Additional RAM must be available for the SnapDrive and VCS applications.
