---
permalink: install/concept-requirements-and-limitations-for-unified-manager-in-mscs.html
sidebar: sidebar
keywords: 
summary: 'Before installing Unified Manager in a failover clustering environment, you must ensure that the cluster nodes are properly configured to support Unified Manager.'
---
= Requirements for Unified Manager in a failover clustering environment
:icons: font
:imagesdir: ../media/

[.lead]
Before installing Unified Manager in a failover clustering environment, you must ensure that the cluster nodes are properly configured to support Unified Manager.

You must ensure that the failover cluster configuration meets the following requirements:

* Both the cluster nodes must be running the same version of Microsoft Windows Server.
* The same version of Unified Manager must be installed using the same path on both the cluster nodes.
* Failover clustering must be installed and enabled on both the nodes.
+
See Microsoft documentation for instructions.

* You must have used Fibre Channel switched fabric or iSCSI-based storage for creating shared data disk as the storage back-end.
* Optional: Using SnapDrive for Windows, a shared location must be created that is accessible to both the nodes in the high-availability setup.
+
See the _SnapDrive for Windows Installation Guide_ for information about installing and creating a shared location.
+
You can also manage LUNs using the storage system command-line interface. See the SnapDrive for Windows compatibility matrix for more information.

* You must have the Perl installed with `XML::LibXML` and `File::chdir` modules for scripts to work.
* There must be only two nodes in the cluster setup.
* The "`node and disk majority`" quorum type must be used for failover clustering.
* You must have configured a shared IP address with a corresponding FQDN to be used as the cluster global IP address to access Unified Manager.
* The password for Unified Manager maintenance user on both the nodes must be same.
* You must have used only IPv4 IP address.
