---
permalink: install/reference_oncommand_unified_manager_product_documentation.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Unified Manager is accompanied by a set of guides that describe how to install and use the product. Online help is also provided in the user interface.'
---
= OnCommand Unified Manager product documentation
:icons: font
:imagesdir: ../media/

[.lead]
OnCommand Unified Manager is accompanied by a set of guides that describe how to install and use the product. Online help is also provided in the user interface.

* *OnCommand Unified Manager Installation Guide*
+
Provides installation, upgrade, and setup instructions for Unified Manager on the VMware, Linux, and Windows platforms.

* *http://docs.netapp.com/ocum-95/topic/com.netapp.doc.onc-um-sysconfig/home.html[OnCommand Unified Manager System Configuration Guide]*
+
Provides initial setup and configuration instructions for Unified Manager. This includes adding clusters, adding users, configuring alerts, and setting up remote authentication.

* *http://docs.netapp.com/ocum-95/topic/com.netapp.doc.onc-um-ag/home.html[OnCommand Unified Manager Workflow Guide for Managing Cluster Health]*
+
Provides information about using Unified Manager to manage and troubleshoot cluster storage health issues. This guide also describes how to use the Unified Manager maintenance console to perform special operations such as restoring a database backup and connecting to an external data provider to offload performance statistics.

* *http://docs.netapp.com/ocum-95/topic/com.netapp.doc.onc-um-perf-ag/home.html[OnCommand Unified Manager Workflow Guide for Managing Cluster Performance]*
+
Provides information about using Unified Manager to manage and troubleshoot cluster storage performance issues. This includes identifying workloads that are overusing cluster components so that you can take corrective action to bring performance back to normal levels of operation.

* *_OnCommand Unified Manager Online Help_*
+
Provides information about using Unified Manager to manage and troubleshoot cluster storage health and performance issues. Additionally, it provides field level descriptions for every UI page in the product. The online help is included with the software, and is also available as a PDF document that you can review offline.
