---
permalink: install/task-upgrading-openjdk-on-windows-ocum.html
sidebar: sidebar
keywords: OnCommand Unified Manager
summary: 'You can upgrade to a newer version of Java Runtime Environment \(JRE\) on the Windows server on which Unified Manager is installed to obtain fixes for security vulnerabilities.'
---
= Upgrading JRE on Windows
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade to a newer version of Java Runtime Environment (JRE) on the Windows server on which Unified Manager is installed to obtain fixes for security vulnerabilities.

== Before you begin

You must have Windows admin privileges for the system on which Unified Manager is installed.

== Steps

. Log in as the admin user on the Unified Manager host machine.
. Download the appropriate version of Java (64-bit) from the JDK site to the target system.
+
For example, download `openjdk-11_windows-x64_bin.zip` from `+http://jdk.java.net/11/+`.

. Use the Windows Services console to stop the following Unified Manager services:
 ** NetApp OCIE Acquisition Unit (Ocie-au)
 ** NetApp OnCommand Application Server (Oncommandsvc)
. Expand the `zip` file.
. Copy the directories and files from the resulting `jdk` directory (for example, `jdk-11.0.1` to the location where Java is installed. Example: `C:\Program Files\NetApp\JDK\`
. Start the Unified Manager services by using the Windows Services console:
 ** NetApp OnCommand Application Server (Oncommandsvc)
 ** NetApp OCIE Acquisition Unit (Ocie-au)
