---
permalink: install/task-deploying-unified-manager-vapp.html
sidebar: sidebar
keywords: 
summary: 'Deploying Unified Manager includes downloading software, deploying the virtual appliance, creating a maintenance user name and password, and performing the initial setup in the web UI.'
---
= Deploying Unified Manager
:icons: font
:imagesdir: ../media/

[.lead]
Deploying Unified Manager includes downloading software, deploying the virtual appliance, creating a maintenance user name and password, and performing the initial setup in the web UI.

== Before you begin

* You must have completed the system requirements for deployment.
+
xref:concept-requirements-for-installing-unified-manager.adoc[System requirements]

* You must have the following information:
 ** Login credentials for the NetApp Support Site
 ** Credentials for accessing the VMware vCenter Server and vSphere Web Client (for vSphere version 6.5) or vSphere Client (for vSphere version 5.5 or 6.0)
 ** IP address of the ESXi server on which you are deploying the Unified Manager virtual appliance
 ** Details about the data center, such as storage space in the datastore and memory requirements
 ** IPv6 must be enabled on the host if you are planning to use IPv6 addressing.
 ** CD-ROM or ISO image of VMware Tools

== About this task

You can deploy Unified Manager as a virtual appliance on a VMware ESXi server.

You must access the maintenance console by using the VMware console, and not by using SSH.

VMware Tools are not included in the Unified Manager``.ova`` file, and must be installed separately.

== After you finish

After finishing the deployment and initial setup, you can either add clusters, or configure additional network settings in the maintenance console, and then access the web UI.
