---
permalink: install/task-restarting-the-unified-manager-virtual-machine.html
sidebar: sidebar
keywords: 
summary: 'You can restart the Unified Manager virtual machine \(VM\) from the maintenance console. You must restart the VM after generating a new security certificate, or if there is a problem with the VM.'
---
= Restarting the Unified Manager virtual machine
:icons: font
:imagesdir: ../media/

[.lead]
You can restart the Unified Manager virtual machine (VM) from the maintenance console. You must restart the VM after generating a new security certificate, or if there is a problem with the VM.

== Before you begin

* The virtual appliance must be powered on.
* You must be logged in to the Unified Manager maintenance console as the maintenance user.

== About this task

You can also restart the virtual machine from vSphere by using the VMware *Restart Guest* option.

== Steps

. In the maintenance console, select *System Configuration* > *Reboot Virtual Machine*.
. Start the Unified Manager graphical user interface (GUI) from your browser, and log in.

*Related information*

https://www.vmware.com/support/developer/PowerCLI/PowerCLI41/html/Restart-VMGuest.html[VMware vSphere PowerCLI Cmdlets Reference: Restart-VMGuest]
