---
permalink: install/task-installing-unified-manager-linux.html
sidebar: sidebar
keywords: 
summary: 'You can install Unified Manager on a physical or virtual Red Hat Enterprise Linux or CentOS platform.'
---
= Installing Unified Manager on Red Hat Enterprise Linux or CentOS
:icons: font
:imagesdir: ../media/

[.lead]
You can install Unified Manager on a physical or virtual Red Hat Enterprise Linux or CentOS platform.

== Before you begin

* The system on which you want to install Unified Manager must meet the system and software requirements.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[Hardware system requirements]
+
xref:reference-red-hat-and-centos-software-and-installation-requirements.adoc[Red Hat and CentOS software and installation requirements]

* You must have downloaded the Unified Manager``.zip`` file from the NetApp Support Site to the target system.
* You must have a supported web browser.
* Your terminal emulation software must have scrollback enabled.

== About this task

The Red Hat Enterprise Linux or CentOS system may have all the required versions of the required supporting software (Java, MySQL, additional utilities) installed, or it may have only some of the required software installed, or it may be a newly installed system with none of the required software installed.

== Steps

. Log in to the server on which you are installing Unified Manager.
. Enter the appropriate commands to assess what software might require installation or upgrade on the target system to support installation:
+
[options="header"]
|===
| Required software and minimum version| Command to verify software and version
a|
OpenJDK version 11
a|
`java -version`
a|
MySQL 5.7.23 Community Edition
a|
`rpm -qa \| grep -i mysql`
a|
p7zip 9.20.1
a|
`rpm -qa \| grep p7zip`
|===

. If any version of the listed software is earlier than the required version, enter the appropriate command to uninstall that module:
+
[options="header"]
|===
| Software to uninstall| Command to uninstall the software
a|
MySQL
[NOTE]
====
Uninstall any version that is not MySQL 5.7.23 Community Edition or later.
====
a|
`rpm -e` <``mysql_package_name``>
[NOTE]
====
If you receive dependency errors, you must add the `--nodeps` option to uninstall the component.
====
a|
All other modules
a|
`yum remove` `module_name`
|===

. Navigate to the directory where you downloaded the installation `.zip` file and expand the Unified Manager bundle: `unzip OnCommandUnifiedManager-rhel7-9.5.zip`
+
The required `.rpm` modules for Unified Manager are unzipped to the target directory.

. Verify that the following modules are available in the directory: `ls *.rpm`
 ** `ocie-au-<version>.x86_64.rpm`
 ** `ocie-server-<version>.x86_64.rpm`
 ** `ocie-serverbase-<version>.x86_64.rpm`
 ** `netapp-application-server-<version>.x86_64.rpm`
 ** `netapp-platform-base-<version>.x86_64.rpm`
 ** `netapp-ocum-<version>.x86_64.rpm`
. Run the pre-installation script to ensure that there are no system configuration settings or any installed software that will conflict with the installation of Unified Manager: `pre_install_check.sh`
+
The pre-installation script checks that the system has a valid Red Hat subscription, and that it has access to the required software repositories. If the script identifies any issues, you must fix the issues prior to installing Unified Manager.
+
[NOTE]
====
You must perform step 7 _only_ if you are required to manually download the packages that are required for your installation. If your system has Internet access and all the required packages are available, go to step 8.
====

. For systems that are not connected to the Internet or that are not using the Red Hat Enterprise Linux repositories, perform the following steps to determine whether you are missing any required packages, and then download those packages:
 .. On the system on which you are installing Unified Manager, view the list of available and unavailable packages: `yum install *.rpm --assumeno`
+
The items in the "`Installing:`" section are the packages that are available in the current directory, and the items in the "`Installing for dependencies:`" section are the packages that are missing on your system.

 .. On a system that has Internet access, download the missing packages: `yum install <package_name\> --downloadonly --downloaddir=.`
+
[NOTE]
====
Because the plug-in "`yum-plugin-downloadonly`" is not always enabled on Red Hat Enterprise Linux systems, you might need to enable the functionality to download a package without installing it: `yum install yum-plugin-downloadonly`
====

 .. Copy the missing packages from the Internet-connected system to your installation system.
. Install the software: `yum install *.rpm`
+
This command installs the `.rpm` packages, all other necessary supporting software, and the Unified Manager software.
+
[NOTE]
====
Do not attempt installation by using alternative commands (such as `+rpm -ivh ...+`). The successful installation of Unified Manager on a Red Hat Enterprise Linux or CentOS system requires that all Unified Manager files and related files are installed in a specific order into a specific directory structure that is enforced automatically by the `yum install *.rpm` command.
====

. Disregard the email notification that is displayed immediately after the installation messages.
+
The email notifies the root user of an initial cron job failure, which has no adverse effect on the installation.

. After the installation messages are complete, scroll back through the messages until you see the message in which the system displays an IP address or URL for the Unified Manager web UI, the maintenance user name (umadmin), and a default password.
+
The message is similar to the following:
+
----
OnCommand Unified Manager installed successfully.
Use a web browser and one of the following URL(s) to configure and access the Unified Manager GUI.
https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/

Log in to Unified Manager in a web browser by using following details:
  username: umadmin
  password: admin
----

. Record the IP address or URL, the assigned user name (umadmin), and the current password.
. If you created a umadmin user account with a custom home directory prior to installing Unified Manager, then you must specify the umadmin user login shell:``usermod -s /bin/maintenance-user-shell.sh umadmin``

== After you finish

You can access the web UI to perform the initial setup of Unified Manager, as described in the _OnCommand Unified Manager System Configuration Guide_.

*Related information*

xref:task-creating-a-custom-user-home-directory-and-umadmin-user-prior-to-installation.adoc[Creating a custom user home directory and umadmin password prior to installation]
