---
permalink: install/task_installing_the_unified_manager_in_vcs_um.html
sidebar: sidebar
keywords: 
summary: 'For configuring high availability, you must install Unified Manager on both the cluster nodes of VCS.'
---
= Installing Unified Manager on VCS
:icons: font
:imagesdir: ../media/

[.lead]
For configuring high availability, you must install Unified Manager on both the cluster nodes of VCS.

== Before you begin

* VCS must be installed and configured on both the nodes of the cluster.
+
See the instructions provided in the _Veritas Cluster Server 6.2.1 Installation Guide_ for more information about installing VCS.

* You must have clear root privileges to log in to the Unified Manager server console.

== About this task

You must configure both the instances of Unified Manager to use the same database and to monitor the same set of nodes.

== Steps

. Log in to the first node of the cluster.
. Install Unified Manager on the first node.
+
link:concept_installing_unified_manager_on_rhel_or_centos.md#[Installing Unified Manager on Red Hat Enterprise Linux or CentOS]

. Repeat Steps 1 and 2 on the second node of the cluster.
. On the second instance of Unified Manager, log in as the root user to the Red Hat Enterprise Linux or CentOS server and enter the same umadmin password as you defined on the first instance of Unified Manager.`passwd umadmin`
