---
permalink: install/task-upgrading-to-unified-manager-on-microsoft-windows.html
sidebar: sidebar
keywords: 
summary: 'You can upgrade Unified Manager 7.3 or 9.4 to Unified Manager 9.5 by downloading and running the installation file on the Windows platform.'
---
= Upgrading Unified Manager on Windows
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade Unified Manager 7.3 or 9.4 to Unified Manager 9.5 by downloading and running the installation file on the Windows platform.

== Before you begin

* The system on which you are upgrading Unified Manager must meet the system and software requirements.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[Hardware system requirements]
+
xref:reference-windows-software-and-installation-requirements.adoc[Windows software and installation requirements]
+
[NOTE]
====
Starting with Unified Manager 9.5, OpenJDK is provided in the Unified Manager installation package and installed automatically. Oracle Java is not supported starting with Unified Manager 9.5.
====
+
[NOTE]
====
Starting with Unified Manager 9.4, Microsoft .NET 4.5.2 or greater is required. Make sure you have the correct version of .NET installed before starting the upgrade.
====

* You must have Windows administrator privileges.
* You must have valid credentials to log in to the NetApp Support Site.
* To avoid data loss, you must have created a backup of the Unified Manager machine in case there is an issue during the upgrade.
* You must have adequate disk space available to perform the upgrade.
+
The available space on the installation drive must be 2.5 GB larger than the size of the data directory. The upgrade will stop and display an error message indicating the amount of space to be added if there is not enough free space.

== About this task

During the upgrade process, Unified Manager is unavailable. You should complete any running operations before upgrading Unified Manager.

If Unified Manager is paired with an instance of OnCommand Workflow Automation, and there are new versions of software available for both products, you must disconnect the two products and then set up a new Workflow Automation connection after performing the upgrades. If you are performing an upgrade to only one of the products, then you should log into Workflow Automation after the upgrade and verify that it is still acquiring data from Unified Manager.

== Steps

. Log in to the NetApp Support Site, and locate the Download page for installing Unified Manager on the Windows platform.
+
http://mysupport.netapp.com/NOW/cgi-bin/software[NetApp Downloads: Software]

. Download the Unified Manager Windows installation file to a target directory in the Windows system.
. If Unified Manager is configured for high availability, stop all the Unified Manager services on the first node by using Microsoft Cluster Server, and then start the MySQL service from `services.msc`.
. Right-click and run the Unified Manager installer executable `(.exe)` file as an administrator.
+
Unified Manager prompts you with the following message:
+
----
This setup will perform an upgrade of ‘OnCommand Unified Manager’. Do you want to continue?
----

. Click *Yes*, and then click *Next*.
. Enter the MySQL root password that was set during installation, and click *Next*.
. After the upgrade is successful, if the system is configured for high availability, start all the Unified Manager services from the Failover Cluster Manager and follow the remaining tasks.
. From the command prompt, run the `ha_setup.pl` script to configure the new services in the failover cluster and the files that are present in the shared location.
+
`C:\Program Files\NetApp\ocum\bin> perl .\ha_setup.pl --upgrade --first -t mscs -g kjaggrp -i "New IP Address1" -n scs8003.englab.company.com -k "Cluster Disk 2" -f E:\ -u user -p userpass`

. Stop all the Unified Manager services (ocie, ocieau, and MySQL) in the first node by using Microsoft Cluster Server.
. Start the MySQL service on the second node from `services.msc`.
. Switch the service group to the second node in the high-availability setup.
. Upgrade Unified Manager on the second node.
. At the command prompt, enter `Y` to continue, or enter any other character to abort.
+
The upgrade and restart processes of the Unified Manager services can take several minutes to complete.

. Start all the Unified Manager services on both the nodes using Microsoft Cluster Server.
. From the command prompt, run the `ha_setup.pl` script with the `--upgrade` option.
+
`perl ha_setup.pl --upgrade --join -t mscs -f E:\`

. Log in to the Unified Manager web UI, and verify the version number.

== After you finish

[NOTE]
====
To perform a silent upgrade of Unified Manager, run the following command: `OnCommandUnifiedManager-9.5.exe /s /v"MYSQL_PASSWORD=netapp21! /qn /l*v C:\install.log`
====
