---
permalink: install/task-changing-the-jboss-password.html
sidebar: sidebar
keywords: 
summary: 'You can create a new, custom JBoss password to overwrite the default password that is set during installation. This task is optional, but some sites might require this security capability to override the Unified Manager installation default setting. This operation also changes the password JBoss uses to access MySQL.'
---
= Changing the JBoss password
:icons: font
:imagesdir: ../media/

[.lead]
You can create a new, custom JBoss password to overwrite the default password that is set during installation. This task is optional, but some sites might require this security capability to override the Unified Manager installation default setting. This operation also changes the password JBoss uses to access MySQL.

== Before you begin

* You must have root user access to the Red Hat Enterprise Linux or CentOS system on which Unified Manager is installed.
* You must be able to access the NetApp-provided `password.sh` script in the directory `/opt/netapp/essentials/bin`.

== Steps

. Log in as root user on the system.
. Stop the Unified Manager services by entering the following commands in the order shown: `service ocieau stop``service ocie stop`
+
Do not stop the associated MySQL software.

. Enter the following command to begin the password change process: `/opt/netapp/essentials/bin/password.sh resetJBossPassword`
. When prompted, enter the old JBoss password.
+
The default password is `D11h1aMu@79%`.

. When prompted, enter the new JBoss password, and then enter it a second time for confirmation.
. When the script completes, start the Unified Manager services by entering the following commands in the order shown: `service ocie start``service ocieau start`
. After all of the services are started, you can log in to the Unified Manager UI.
