---
permalink: install/task-manually-configuring-the-mysql-repository.html
sidebar: sidebar
keywords: Unified Manager
summary: 'If the system on which you are installing Unified Manager does not have access to the MySQL Community Edition repository, then you must manually download and configure the repository for a successful installation.'
---
= Manually configuring the MySQL repository
:icons: font
:imagesdir: ../media/

[.lead]
If the system on which you are installing Unified Manager does not have access to the MySQL Community Edition repository, then you must manually download and configure the repository for a successful installation.

== About this task

The MySQL repository provides access to the required MySQL software that must be installed on your system.

[NOTE]
====
This task will fail if the system does not have Internet connectivity. Refer to the MySQL documentation if the system on which you are installing Unified Manager does not have Internet access.
====

== Steps

. Download the appropriate MySQL repository for your installation: `+wget http://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/mysql57-community-release-el7-7.noarch.rpm+`
. Configure the MySQL repository: `yum install mysql57-community-release-el7-7.noarch.rpm`
