---
permalink: install/task-upgrading-mysql-on-windows-ocum.html
sidebar: sidebar
keywords: OnCommand Unified Manager
summary: 'You can upgrade to a newer version of MySQL on the Windows server on which Unified Manager is installed to obtain fixes for security vulnerabilities.'
---
= Upgrading MySQL on Windows
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade to a newer version of MySQL on the Windows server on which Unified Manager is installed to obtain fixes for security vulnerabilities.

== Before you begin

* You must have Windows admin privileges for the system on which Unified Manager is installed.
* You must have the password for the MySQL root user.

== Steps

. Log in as the admin user on the Unified Manager host machine.
. Download the appropriate version of MySQL to the target system.
. Use the Windows Services console to stop the following Unified Manager services:
 ** NetApp OCIE Acquisition Unit (Ocie-au)
 ** NetApp OnCommand Application Server (Oncommandsvc)
 ** MYSQL
. Click the `.msi` package to invoke the upgrade of MySQL and follow the instructions on the screen to complete the upgrade.
. Start the Unified Manager services by using the Windows Services console:
 ** MYSQL
 ** NetApp OnCommand Application Server (Oncommandsvc)
 ** NetApp OCIE Acquisition Unit (Ocie-au)
