---
permalink: install/task_removing_unified_manager_vapp.html
sidebar: sidebar
keywords: 
summary: 'You can uninstall Unified Manager by destroying the virtual appliance on which the Unified Manager software is installed.'
---
= Removing Unified Manager from VMware
:icons: font
:imagesdir: ../media/

[.lead]
You can uninstall Unified Manager by destroying the virtual appliance on which the Unified Manager software is installed.

== Before you begin

* You must have credentials for accessing VMware vCenter Server and vSphere Web Client (for vSphere version 6.5) or vSphere Client (for vSphere version 5.5 or 6.0).
* The Unified Manager server must not have an active connection to an external data provider.
+
If there is an active connection, you must delete the connection by using the Unified Managermaintenance console.

* The Unified Manager server must not have an active connection to a Workflow Automation server.
+
If there is an active connection, you must delete the connection by using the Administration menu.

* All clusters (data sources) must be removed from the Unified Manager server before you delete the virtual machine (VM).

== Steps

. Use the Unified Managermaintenance console to verify that the Unified Manager server does not have an active connection to an external data provider.
. In the vSphere Client, click *Home* > *Inventory* > *VMs and Templates*.
. Select the VM that you want to destroy, and click the *Summary* tab.
. If the VM is running, click *Power* > *Shut Down Guest*.
. Right-click the VM that you want to destroy, and click *Delete from Disk*.
