---
permalink: install/task-configuring-existing-unified-manager-setup-to-high-availability.html
sidebar: sidebar
keywords: 
summary: 'You can update your existing Unified Manager installation and configure your setup environment for high availability.'
---
= Updating an existing Unified Manager setup for high availability
:icons: font
:imagesdir: ../media/

[.lead]
You can update your existing Unified Manager installation and configure your setup environment for high availability.

== Before you begin

* You must have created a backup and support bundle of your existing data.
* You must have the OnCommand Administrator or Storage Administrator role.
* You must have added a second node to your cluster and installed Veritas Cluster Server (VCS) on the second node.
+
See the _Veritas Cluster Server 6.2.1 Installation Guide_.

* The newly added node must be configured to access the same shared location as that of the existing node in the high-availability setup.

== Steps

. Log in to the new node of the cluster.
. Install Unified Manager on the node.
+
xref:concept-installing-unified-manager-on-rhel-or-centos.adoc[Installing Unified Manager on Red Hat Enterprise Linux or CentOS]

. Configure the Unified Manager server using configuration scripts on the existing node with data.
. Initiate manual fail over to the second node.
. Run the `perl ha_setup.pl --join -t vcs -f``mount_path` command on the second node of the cluster so that the Unified Manager server data points to the shared LUN.
. If OnCommand Workflow Automation (WFA) is configured for Unified Manager, disable and then reconfigure the WFA connection.
. If SnapProtect is configured with Unified Manager, reconfigure SnapProtect with a new cluster IP address and the existing storage policies.
. Regenerate the custom reports and add these reports to Unified Manager with the new cluster IP address.
