---
permalink: install/task-removing-unified-manager.html
sidebar: sidebar
keywords: 
summary: 'If you need to remove Unified Manager from the Red Hat Enterprise Linux or CentOS host, you can stop and uninstall Unified Manager with a single command.'
---
= Removing Unified Manager from the Red Hat Enterprise Linux or CentOS host
:icons: font
:imagesdir: ../media/

[.lead]
If you need to remove Unified Manager from the Red Hat Enterprise Linux or CentOS host, you can stop and uninstall Unified Manager with a single command.

== Before you begin

* You must have root user access to the server from which you want to remove Unified Manager.
* Security-Enhanced Linux (SELinux) must be disabled on the Red Hat machine. Change the SELinux runtime mode to "`Permissive`" by using the `setenforce 0` command.
* All clusters (data sources) must be removed from the Unified Manager server before removing the software.
* The Unified Manager server must not have an active connection to an external data provider such as Graphite.
+
If it does, you must delete the connection using the Unified Managermaintenance console.

== About this task

These steps contain information for systems that are configured for high availability using Veritas Operation Manager. If your system is not configured for high availability, ignore these additional steps.

== Steps

. Log in as root user to the cluster node owning the cluster resources on which you want to remove Unified Manager.
. Stop all Unified Manager services using VCS Operations Manager or VCS commands.
. Stop and remove Unified Manager from the server: `rpm -e netapp-ocum ocie-au ocie-server netapp-platform-base netapp-application-server ocie-serverbase`
+
This step removes all the associated NetApp RPM packages. It does not remove the prerequisite software modules, such as Java, MySQL, and p7zip.

. Switch to the other node by using the VCS Operations Manager.
. Log in to the second node of the cluster.
. Stop all the services, and then and remove Unified Manager from the second node: `rpm -e netapp-ocum ocie-au ocie-server netapp-platform-base netapp-application-server ocie-serverbase`
. Prevent the service group from using VCS Operations Manager or VCS commands.
. If appropriate, remove the supporting software modules, such as Java, MySQL, and p7zip: `rpm -e p7zip mysql-community-client mysql-community-server mysql-community-common mysql-community-libs java-x.y`

== Results

After this operation is complete, the software is removed; however, MySQL data is not deleted. All the data from the `/opt/netapp/data` directory is moved to the `/opt/netapp/data/BACKUP` folder after uninstallation.
