---
permalink: install/task-installing-unified-manager-on-windows.html
sidebar: sidebar
keywords: 
summary: 'You can install Unified Manager on Windows to monitor and troubleshoot data storage capacity, availability, performance, and protection issues.'
---
= Installing Unified Manager on a Windows system
:icons: font
:imagesdir: ../media/

[.lead]
You can install Unified Manager on Windows to monitor and troubleshoot data storage capacity, availability, performance, and protection issues.

== Before you begin

* The system on which you plan to install Unified Manager must meet the system and software requirements.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[Hardware system requirements]
+
xref:reference-windows-software-and-installation-requirements.adoc[Windows software and installation requirements]
+
[NOTE]
====
Starting with Unified Manager 9.5, OpenJDK is provided in the Unified Manager installation package and installed automatically. Oracle Java is not supported starting with Unified Manager 9.5.
====

* You must have Windows administrator privileges.
* You must have a supported web browser.
* The Unified Manager maintenance user password must be between 8 and 20 characters, must contain upper-case letters or lower-case letters, numerals, and special characters.
* The following special characters are not allowed in the password string for the maintenance user or for the MySQL root user: " ' ` % , = & < > | {caret} \ / ( ) [ ] ;
+
The following special characters are allowed: ~ ! @ # $ * - ? . : + { }

== Steps

. Log in to Windows using the default local administrator account.
. Log in to the NetApp Support Site, and locate the Download page for installing Unified Manager on the Windows platform.
+
http://mysupport.netapp.com/NOW/cgi-bin/software[NetApp Downloads: Software]

. Download the Unified Manager Windows installation file from the NetApp Support Site to a target directory in the Windows system.
. Navigate to the directory where the installation file is located.
. Right-click and run the Unified Manager installer executable (`.exe`) file as an administrator.
+
Unified Manager detects missing or pre-installed third-party packages and lists them. If the required third-party packages are not installed in the system, Unified Manager installs them as part of the installation.

. Click *Next*.
. Enter the user name and password to create the maintenance user.
. In the *Database Connection* wizard, enter the MySQL root password.
. Click *Change* to specify a new location for the Unified Manager installation directory and MySQL data directory.
+
If you do not change the installation directory, Unified Manager is installed in the default installation directory.

. Click *Next*.
. In the *Ready to Install Shield* wizard, click *Install*.
. After the installation is complete, click *Finish*.

== Results

The installation creates multiple directories:

* Installation directory
+
This is the root directory for Unified Manager, which you specified during installation. Example: `C:\Program Files\NetApp\`

* MySQL data directory
+
This is the directory where the MySQL databases are stored, which you specified during installation. Example: `C:\ProgramData\MySQL\MySQLServerData\`

* Java directory
+
This is the directory where OpenJDK will be installed. Example: `C:\Program Files\NetApp\JDK\`

* Unified Manager application data directory (appDataDir)
+
This is the directory where all the application-generated data is stored. This includes logs, support bundles, backup, and all other additional data. Example: `C:\ProgramData\NetApp\OnCommandAppData\`

== After you finish

You can access the web UI to perform the initial setup of Unified Manager, as described in the http://docs.netapp.com/ocum-95/topic/com.netapp.doc.onc-um-sysconfig/home.html[OnCommand Unified Manager System Configuration Guide].
